using System;
using System.Globalization;
using System.Windows;

namespace CalradiaForge.Desktop.Services
{
    /// <summary>Formats a localized resource template; generated code itself stays untouched.</summary>
    internal static class DesktopTemplateLocalizer
    {
        public static string Prefix(string toolId, string template)
        {
            var header = Application.Current?.TryFindResource("Ui.TemplateHeader") as string
                ?? "Generated by Calradia Forge for {0}. Review this editable starting point.";
            return "// " + string.Format(CultureInfo.CurrentCulture, header, toolId ?? "tool") + Environment.NewLine + (template ?? string.Empty);
        }
    }
}
