import json

tooltips_es = {
    "SubModuleValidator": "Valida el esquema de SubModule.xml, entradas DLL y dependencias de módulos.",
    "ModConflictMatrix": "Detecta conflictos de IDs en entidades XML y el orden de sobreescritura entre mods instalados.",
    "XmlSchemaValidator": "Comprueba la sintaxis XML bien formada y las reglas de seguridad DTD.",
    "WatchdogParser": "Analiza los registros watchdog de TaleWorlds para aislar excepciones no controladas y fallos nativos.",
    "CrashAnalyzer": "Analiza los registros de volcados .cfcrash y direcciones de memoria.",
    "ApiDeprecationChecker": "Escanea los archivos fuente C# en busca de usos de API obsoletas de TaleWorlds.",
    "PackagingAuditor": "Verifica los metadatos de ensamblado en .csproj y asegura que los scripts de compilación sean excluidos de los archivos de lanzamiento.",
    "MissionMeshGuard": "Comprueba que la creación de mallas/esqueletos se aplace después de OnInit usando la guardia _initialized.",
    "SaveTypeDefinerAuditor": "Verifica que los IDs base de SaveableTypeDefiner personalizados sean >= 2,500,000 para prevenir corrupción de guardados.",
    "GauntletEventPassChecker": "Audita widgets de fondo decorativos buscando DoNotAcceptEvents y DoNotPassEventsToChildren.",
    "CampaignNamespaceGuard": "Aplica la regla GEMINI.md: prohíbe que las carpetas, espacios de nombres o clases se llamen 'Campaign'.",
    "ModIdAuditor": "Detecta colisiones de espacios de nombres entre IDs de mods y los módulos nativos de TaleWorlds.",
    "AudioFmodMixerInspector": "Audita los buses del mezclador module_sounds.xml, categorías y reglas de codificación.",
    "LiveConsole": "Consola de desarrollo interactiva conectada a Bannerlord a través de tuberías con nombre.",
    "ObjectInspector": "Inspector de reflexión en vivo para entidades del juego en tiempo de ejecución (Héroes, Asentamientos, Grupos).",
    "SaveInspector": "Inspección en vivo de los datos guardados de la campaña de Bannerlord y del registro SaveableTypeDefiner.",
    "SaveBinaryParser": "Analiza encabezados binarios .sav, manifiestos de módulos y cadenas serializadas.",
    "MemoryProfiler": "Rastrea el consumo de memoria y la asignación de desprendimientos durante las escenas de asedio.",
    "GauntletInspector": "Audita la jerarquía XML de Gauntlet y busca errores comunes en la interfaz de usuario.",
    "GauntletLivePreview": "Renderiza una maqueta visual simulada de prefabricados XML de Gauntlet.",
    "PartyInventory": "Inspecciona las listas de elementos del grupo y previene desbordamientos de conteo negativo.",
    "MapPathfindingDebugger": "Calcula distancias geodésicas en el mapa de campaña y costos de terreno.",
    "SoundXmlSynthesizer": "Genera definiciones module_sounds.xml con los buses de mezclador 2D/3D correctos.",
    "TroopXmlSynthesizer": "Genera NPCCharacters.xml válidos con edades enteras y ranuras de equipamiento.",
    "ItemXmlSynthesizer": "Genera Items.xml para armas, armaduras, escudos y piezas de artesanía.",
    "WeaponCraftingForge": "Simula estadísticas de herrería de armas, longitudes de hoja y valores de daño.",
    "BrushSynthesizer": "Sintetiza estilos de Brushes.xml de Gauntlet con la paleta Tactical War Theme.",
    "XmlSnippetForge": "Proporciona plantillas XML listas para copiar y pegar para módulos de Bannerlord.",
    "LocalizationHashGenerator": "Calcula identificadores de cadena deterministas SHA-256 para la localización de Bannerlord.",
    "LocalizationMatrix": "Cuadrícula de cobertura de traducción multilingüe en los módulos instalados.",
    "ItemBalanceAnalyzer": "Compara las proporciones de daño, armadura y peso de los objetos frente a los niveles nativos.",
    "TroopTreeVisualizer": "Visualiza las ramas de progresión de tropas y las rutas de actualización.",
    "PerkTreeCalculator": "Modela las tasas de progresión de habilidades, multiplicadores de ventajas y límites de aprendizaje.",
    "DiplomaticMatrix": "Evalúa la fuerza militar de las facciones, viabilidad de guerra y saldos de tributos.",
    "SettlementCalculator": "Calcula el equilibrio de prosperidad de los asentamientos, seguridad alimentaria y riesgos de rebelión.",
    "PartyCalculator": "Simula fórmulas de velocidad del grupo, costos salariales y equilibrio de composición.",
    "CombatAgentSpawner": "Genera planos procesales de grupos de combate con anulaciones de equipamiento.",
    "MockEngine": "Simula ticks de la campaña de Bannerlord sin cabeza para pruebas fuera de línea.",
    "WorkshopEnterpriseSimulator": "Simula la oferta del mercado, ROI, salarios y lotes de producción entre ciudades.",
    "SiegeNavmeshTactician": "Evalúa la probabilidad de brechas, efectividad de la maquinaria y navmeshes dinámicos.",
    "WarCasusBelliEngine": "Calcula puntuaciones geopolíticas de casus belli, votaciones de consejo y tributos.",
    "ModPackager": "Empaqueta el módulo en un archivo zip limpio de distribución sin scripts.",
    "DependencySorter": "Calcula los órdenes de carga de módulos válidos utilizando el ordenamiento topológico de Kahn.",
    "HarmonyPatcher": "Genera plantillas de parches Prefix, Postfix y Transpiler con seguridad contra eliminación de parches.",
    "HarmonyTranspiler": "Valida las instrucciones de manipulación de código IL en los transpiladores Harmony.",
    "QuestDialogBuilder": "Genera la clase QuestBase con tokens de conversación y el método dual SetDialogs().",
    "RecentExports": "Muestra y administra archivos generados recientemente.",
    "SdkCheatSheet": "Guía rápida de referencias a las API del motor de TaleWorlds y a las reglas del ciclo de vida.",
    "ShortcutGuide": "Guía completa de atajos de teclado del banco de trabajo y dentro del juego.",
    "ConsoleReference": "Directorio de comandos estándar para la consola de desarrollo.",
    "NoviceBehavior": "Genera una clase CampaignBehaviorBase completa con escuchas de eventos y sincronización de guardado.",
    "NoviceTroop": "Genera una entrada de tropa válida en NPCCharacters.xml con equipamiento, habilidades y mejoras.",
    "NoviceQuest": "Genera una clase QuestBase completa con el método dual SetDialogs() y SaveableTypeDefiner.",
    "NoviceItem": "Genera Items.xml para armas, armaduras, escudos o caballos con estadísticas de daño.",
    "NoviceSubmodule": "Genera un manifiesto SubModule.xml completo y válido con dependencias y etiquetas.",
    "NoviceChecklist": "Ejecuta una lista de control completa de 6 puntos antes de publicar tu mod.",
    "NoviceEvents": "Explora explicaciones, cuándo utilizarlos y los patrones de suscripción para 28 CampaignEvents.",
    "NoviceHint": "Genera enlaces Hint.HintText de Gauntlet, tooltips multilínea y cadenas de localización.",
    "NoviceWorkshop": "Genera workshops.xml y CampaignBehavior con prevención de desbordamientos negativos.",
    "NoviceParty": "Genera partyTemplates.xml y un generador programático de grupos de bandidos seguro para guardados.",
    "NoviceBuilding": "Genera buildings.xml y un decorador ExplainedNumber de GameModel.",
    "NoviceCombatAi": "Genera AgentComponent y MissionLogic con inicialización pospuesta."
}

tooltips_fr = {
    "SubModuleValidator": "Valide le schéma de SubModule.xml, les entrées DLL et les dépendances de modules.",
    "ModConflictMatrix": "Détecte les conflits d'IDs d'entités XML et l'ordre d'écrasement entre les mods installés.",
    "XmlSchemaValidator": "Vérifie la syntaxe XML bien formée et les règles de sécurité DTD.",
    "WatchdogParser": "Analyse les journaux watchdog de TaleWorlds pour isoler les exceptions non gérées et les crashs natifs.",
    "CrashAnalyzer": "Analyse les journaux de plantages .cfcrash et les adresses mémoire.",
    "ApiDeprecationChecker": "Analyse les fichiers source C# pour les utilisations d'API obsolètes de TaleWorlds.",
    "PackagingAuditor": "Vérifie les métadonnées de l'assembly dans .csproj et s'assure que les scripts de build sont exclus des archives de publication.",
    "MissionMeshGuard": "Vérifie que la création de maillages/squelettes est reportée après OnInit avec la garde _initialized.",
    "SaveTypeDefinerAuditor": "Vérifie que les IDs de base de SaveableTypeDefiner sont >= 2 500 000 pour éviter la corruption de sauvegarde.",
    "GauntletEventPassChecker": "Audit les widgets d'arrière-plan décoratifs pour DoNotAcceptEvents et DoNotPassEventsToChildren.",
    "CampaignNamespaceGuard": "Applique la règle GEMINI.md: interdit que les dossiers, namespaces ou classes soient nommés 'Campaign'.",
    "ModIdAuditor": "Détecte les collisions de namespaces entre les ID de mods et les modules natifs TaleWorlds.",
    "AudioFmodMixerInspector": "Audite les bus de mixage module_sounds.xml, les catégories et les règles d'encodage.",
    "LiveConsole": "Console de développement interactive connectée à Bannerlord via un named pipe.",
    "ObjectInspector": "Inspecteur de réflexion en direct pour les entités du jeu à l'exécution (Héros, Fiefs, Groupes).",
    "SaveInspector": "Inspection en direct des données de sauvegarde de campagne de Bannerlord et du registre SaveableTypeDefiner.",
    "SaveBinaryParser": "Analyse les en-têtes binaires .sav, les manifestes de module et les chaînes sérialisées.",
    "MemoryProfiler": "Suit la consommation de mémoire et l'allocation des détachements lors des scènes de siège.",
    "GauntletInspector": "Audit la hiérarchie XML de Gauntlet et vérifie les bogues courants d'interface utilisateur.",
    "GauntletLivePreview": "Affiche une maquette visuelle des préfabriqués XML de Gauntlet.",
    "PartyInventory": "Inspecte les inventaires de groupe et empêche les dépassements de comptage négatif.",
    "MapPathfindingDebugger": "Calcule les distances géodésiques de la carte de campagne et les coûts du terrain.",
    "SoundXmlSynthesizer": "Génère des définitions module_sounds.xml avec les bus de mixage 2D/3D corrects.",
    "TroopXmlSynthesizer": "Génère des NPCCharacters.xml valides avec des âges entiers et des emplacements d'équipement.",
    "ItemXmlSynthesizer": "Génère Items.xml pour les armes, armures, boucliers et composants de forge.",
    "WeaponCraftingForge": "Simule les statistiques de forge des armes, les longueurs de lame et les valeurs de dégâts.",
    "BrushSynthesizer": "Synthétise les styles Brushes.xml de Gauntlet avec la palette Tactical War Theme.",
    "XmlSnippetForge": "Fournit des modèles XML prêts à copier-coller pour les modules Bannerlord.",
    "LocalizationHashGenerator": "Calcule des identifiants de chaînes SHA-256 déterministes pour la localisation de Bannerlord.",
    "LocalizationMatrix": "Grille de couverture de traduction multilingue sur les modules installés.",
    "ItemBalanceAnalyzer": "Compare les ratios de dégâts, d'armure et de poids des objets avec les niveaux natifs.",
    "TroopTreeVisualizer": "Visualise les branches de progression des troupes et les chemins d'amélioration.",
    "PerkTreeCalculator": "Modélise les taux d'apprentissage de compétences, les modificateurs de perks et les limites d'apprentissage.",
    "DiplomaticMatrix": "Évalue les forces militaires des factions, la viabilité de la guerre et les bilans des tributs.",
    "SettlementCalculator": "Calcule l'équilibre de la prospérité des fiefs, la sécurité alimentaire et les risques de rébellion.",
    "PartyCalculator": "Simule les formules de vitesse des groupes, les coûts salariaux et l'équilibre des compositions.",
    "CombatAgentSpawner": "Génère des schémas de groupes de combat procéduraux avec des remplacements d'équipement.",
    "MockEngine": "Simule les ticks de campagne Bannerlord sans interface pour les tests hors ligne.",
    "WorkshopEnterpriseSimulator": "Simule l'offre du marché, le ROI, les salaires et la production dans les villes.",
    "SiegeNavmeshTactician": "Évalue la probabilité des brèches, l'efficacité de la machinerie et les navmeshes dynamiques.",
    "WarCasusBelliEngine": "Calcule les scores géopolitiques du casus belli, le vote du conseil et le tribut.",
    "ModPackager": "Regroupe le module dans une archive zip propre pour distribution sans scripts.",
    "DependencySorter": "Calcule l'ordre de chargement valide des modules en utilisant le tri topologique de Kahn.",
    "HarmonyPatcher": "Génère des modèles de patch Prefix, Postfix et Transpiler avec une protection contre les bugs d'unpatch.",
    "HarmonyTranspiler": "Valide les instructions de manipulation de code IL dans les transpileurs Harmony.",
    "QuestDialogBuilder": "Génère une classe QuestBase avec les jetons de conversation et la méthode double SetDialogs().",
    "RecentExports": "Affiche et gère les fichiers générés récemment.",
    "SdkCheatSheet": "Guide de référence rapide pour les API du moteur TaleWorlds et les règles du cycle de vie.",
    "ShortcutGuide": "Guide complet des raccourcis clavier de l'atelier et du jeu.",
    "ConsoleReference": "Annuaire des commandes standard de la console de développement.",
    "NoviceBehavior": "Génère une classe CampaignBehaviorBase complète avec écoute d'événements et synchronisation de sauvegarde.",
    "NoviceTroop": "Génère une entrée de troupe valide NPCCharacters.xml avec équipement, compétences et améliorations.",
    "NoviceQuest": "Génère une classe QuestBase complète avec la méthode double SetDialogs() et SaveableTypeDefiner.",
    "NoviceItem": "Génère Items.xml pour les armes, armures, boucliers ou chevaux avec des statistiques de dégâts.",
    "NoviceSubmodule": "Génère un manifeste SubModule.xml valide et complet avec dépendances et balises.",
    "NoviceChecklist": "Exécute une liste de contrôle en 6 points avant de publier votre mod.",
    "NoviceEvents": "Parcourez les explications, les cas d'utilisation et les modèles d'abonnement de 28 CampaignEvents.",
    "NoviceHint": "Génère des liaisons Hint.HintText Gauntlet, des info-bulles multilignes et des chaînes de localisation.",
    "NoviceWorkshop": "Génère workshops.xml et CampaignBehavior avec protection contre les dépassements négatifs.",
    "NoviceParty": "Génère partyTemplates.xml et un générateur de groupes de bandits sans risque pour les sauvegardes.",
    "NoviceBuilding": "Génère buildings.xml et un décorateur ExplainedNumber GameModel.",
    "NoviceCombatAi": "Génère AgentComponent et MissionLogic avec initialisation différée."
}

tooltips_tr = {
    "SubModuleValidator": "SubModule.xml şemasını, DLL girdilerini ve modül bağımlılıklarını doğrular.",
    "ModConflictMatrix": "Yüklü modlar arasında XML varlık kimliği çakışmalarını ve son yükleme üzerine yazma sırasını algılar.",
    "XmlSchemaValidator": "İyi biçimlendirilmiş XML sözdizimini ve DTD güvenlik kurallarını kontrol eder.",
    "WatchdogParser": "İşlenmemiş istisnaları ve yerel çökmeleri izole etmek için TaleWorlds bekçi günlüğü ayrıştırır.",
    "CrashAnalyzer": ".cfcrash döküm günlüklerini ve bellek adreslerini analiz eder.",
    "ApiDeprecationChecker": "Kullanımdan kaldırılmış TaleWorlds API kullanımları için C# kaynak dosyalarını tarar.",
    "PackagingAuditor": ".csproj içindeki montaj meta verilerini doğrular ve derleme komut dosyalarının sürüm arşivlerinden çıkarılmasını sağlar.",
    "MissionMeshGuard": "Ağ / iskelet oluşturma işleminin _initialized kullanılarak OnInit sonrasına ertelendiğini kontrol eder.",
    "SaveTypeDefinerAuditor": "Kayıt bozulmasını önlemek için özel SaveableTypeDefiner temel ID'lerinin >= 2,500,000 olduğunu doğrular.",
    "GauntletEventPassChecker": "DoNotAcceptEvents ve DoNotPassEventsToChildren için dekoratif arka plan araçlarını denetler.",
    "CampaignNamespaceGuard": "GEMINI.md kuralını zorlar: klasör, ad alanı veya sınıfların 'Campaign' olarak adlandırılmasını yasaklar.",
    "ModIdAuditor": "Mod ID'leri ile yerel TaleWorlds modülleri arasındaki ad alanı çakışmalarını algılar.",
    "AudioFmodMixerInspector": "module_sounds.xml karıştırıcı veri yollarını, kategorileri ve kodlama kurallarını denetler.",
    "LiveConsole": "İsimlendirilmiş boru (named pipe) üzerinden Bannerlord'a bağlı etkileşimli geliştirici konsolu.",
    "ObjectInspector": "Çalışma zamanı oyun varlıkları (Kahramanlar, Yerleşimler, Birlikler) için canlı yansıma denetçisi.",
    "SaveInspector": "Bannerlord sefer kayıt verilerinin ve SaveableTypeDefiner kayıtlarının canlı denetimi.",
    "SaveBinaryParser": "İkili .sav başlıklarını, modül bildirimlerini ve serileştirilmiş dizeleri ayrıştırır.",
    "MemoryProfiler": "Kuşatma sahnelerinde bellek tüketimini ve ayrılma tahsisini izler.",
    "GauntletInspector": "Gauntlet XML hiyerarşisini denetler ve genel UI hatalarını kontrol eder.",
    "GauntletLivePreview": "Gauntlet XML şablonlarının sahte görsel düzenini oluşturur.",
    "PartyInventory": "Birlik öğe listelerini inceler ve negatif sayım taşmalarını önler.",
    "MapPathfindingDebugger": "Sefer haritası jeodezik mesafelerini ve arazi maliyetlerini hesaplar.",
    "SoundXmlSynthesizer": "Doğru 2D/3D karıştırıcı yollarıyla module_sounds.xml tanımları üretir.",
    "TroopXmlSynthesizer": "Tam sayı yaşlar ve donanım yuvaları içeren geçerli NPCCharacters.xml üretir.",
    "ItemXmlSynthesizer": "Silahlar, zırhlar, kalkanlar ve zanaat parçaları için Items.xml üretir.",
    "WeaponCraftingForge": "Silah demirciliği istatistiklerini, bıçak uzunluklarını ve hasar değerlerini simüle eder.",
    "BrushSynthesizer": "Tactical War Theme paletiyle Gauntlet Brushes.xml stillerini sentezler.",
    "XmlSnippetForge": "Bannerlord modülleri için kopyala-yapıştır yapmaya hazır XML şablonları sağlar.",
    "LocalizationHashGenerator": "Bannerlord yerelleştirmesi için belirleyici SHA-256 dize kimliklerini hesaplar.",
    "LocalizationMatrix": "Yüklü modüller üzerinde çok dilli çeviri kapsama ızgarası.",
    "ItemBalanceAnalyzer": "Öğe hasar, zırh ve ağırlık oranlarını yerel aşamalarla karşılaştırır.",
    "TroopTreeVisualizer": "Birlik ilerleme dallarını ve yükseltme yollarını görselleştirir.",
    "PerkTreeCalculator": "Beceri ilerleme oranlarını, yetenek çarpanlarını ve öğrenme sınırlarını modeller.",
    "DiplomaticMatrix": "Taraf askeri güçlerini, savaş kapasitesini ve haraç bakiyelerini değerlendirir.",
    "SettlementCalculator": "Yerleşim refah dengesini, gıda güvenliğini ve isyan risklerini hesaplar.",
    "PartyCalculator": "Birlik hız formüllerini, maaş maliyetlerini ve kompozisyon dengesini simüle eder.",
    "CombatAgentSpawner": "Donanım geçersiz kılmaları ile usule uygun savaş birliği taslakları üretir.",
    "MockEngine": "Çevrimdışı testler için başsız Bannerlord sefer tiklerini simüle eder.",
    "WorkshopEnterpriseSimulator": "Şehirler arası piyasa arzı, ROI, maaşlar ve üretim partilerini simüle eder.",
    "SiegeNavmeshTactician": "Gedik olasılığını, makine etkinliğini ve dinamik hareket ağlarını değerlendirir.",
    "WarCasusBelliEngine": "Jeopolitik savaş sebebi puanlarını, konsey oylamasını ve haracı hesaplar.",
    "ModPackager": "Modülü komut dosyaları olmadan temiz zip dağıtım arşivine paketler.",
    "DependencySorter": "Kahn'ın topolojik sıralamasını kullanarak geçerli modül yükleme sıralarını hesaplar.",
    "HarmonyPatcher": "Yama kaldırma güvenliği olan Prefix, Postfix ve Transpiler yama taslakları oluşturur.",
    "HarmonyTranspiler": "Harmony transpilatörlerinde IL kodu manipülasyon talimatlarını doğrular.",
    "QuestDialogBuilder": "Konuşma belirteçleri ve çift SetDialogs() yöntemiyle QuestBase sınıfı oluşturur.",
    "RecentExports": "Yakın zamanda oluşturulan dosya taslaklarını listeler ve yönetir.",
    "SdkCheatSheet": "TaleWorlds motor API'leri ve yaşam döngüsü kuralları için hızlı başvuru kılavuzu.",
    "ShortcutGuide": "Çalışma tezgahı ve oyun içi kısayollarının kapsamlı kopya kağıdı.",
    "ConsoleReference": "Standart geliştirici konsolu komutları dizini.",
    "NoviceBehavior": "Olay dinleyicileri ve kayıt senkronizasyonu ile eksiksiz bir CampaignBehaviorBase sınıfı oluşturun.",
    "NoviceTroop": "Ekipman, beceriler ve yükseltmelerle geçerli bir NPCCharacters.xml birlik girişi oluşturun.",
    "NoviceQuest": "Çift SetDialogs() ve SaveableTypeDefiner içeren eksiksiz bir QuestBase sınıfı oluşturun.",
    "NoviceItem": "Hasar istatistikleriyle silah, zırh, kalkan veya atlar için Items.xml oluşturun.",
    "NoviceSubmodule": "Bağımlılıklar ve etiketlerle geçerli, eksiksiz bir SubModule.xml bildirimi oluşturun.",
    "NoviceChecklist": "Modunuzu yayınlamadan önce 6 noktalı kapsamlı bir ön kontrol listesi çalıştırın.",
    "NoviceEvents": "28 CampaignEvents için açıklamaları, ne zaman kullanılacağını ve abonelik kalıplarını keşfedin.",
    "NoviceHint": "Gauntlet Hint.HintText bağlamaları, çok satırlı ipuçları ve yerelleştirme dizeleri oluşturun.",
    "NoviceWorkshop": "Negatif taşma güvenliği ile workshops.xml ve CampaignBehavior oluşturun.",
    "NoviceParty": "partyTemplates.xml ve kayıt korumalı programlanabilir haydut oluşturucu üretin.",
    "NoviceBuilding": "buildings.xml ve GameModel ExplainedNumber dekoratör sınıfı oluşturun.",
    "NoviceCombatAi": "Gecikmeli başlatma ile AgentComponent ve MissionLogic oluşturun."
}

with open('tooltips_en.json', 'r', encoding='utf-8') as f:
    tooltips_en = json.load(f)

lines = []
for tag in tooltips_en.keys():
    en = tooltips_en[tag].replace('"', '\\"')
    es = tooltips_es[tag].replace('"', '\\"')
    fr = tooltips_fr[tag].replace('"', '\\"')
    tr = tooltips_tr[tag].replace('"', '\\"')
    lines.append(f'                                "{tag}" => isEs ? "{es}" : isFr ? "{fr}" : isTr ? "{tr}" : "{en}",')

with open('tooltips_switch.cs', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))
print("Generated tooltips_switch.cs")
