using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using System.Xml.Linq;

namespace CalradiaForge.Sdk
{
    /// <summary>
    /// Novice Modder Hub — generates ready-to-paste C# scaffolds and XML templates
    /// with pedagogical inline comments so beginner modders understand every line.
    /// All generators are stateless and produce self-contained output strings.
    /// </summary>
    public static class ForgeNoviceHub
    {
        private static readonly HashSet<string> ReservedCSharpKeywords = new HashSet<string>(StringComparer.Ordinal)
        {
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
            "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
            "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
            "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
            "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
            "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short",
            "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true",
            "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual",
            "void", "volatile", "while"
        };

        // ─────────────────────────────────────────────────────────────────
        // 1. CampaignBehaviorBase Scaffold
        // ─────────────────────────────────────────────────────────────────

        /// <summary>
        /// Generates a fully annotated CampaignBehaviorBase C# class.
        /// Follows the double-SyncData guard pattern and stable-ID buckets for eligible optional batch work.
        /// </summary>
        public static string GenerateBehaviorScaffold(string className = "MyForgeBehavior", string ns = "MyMod.CampaignBehaviors")
        {
            if (string.IsNullOrWhiteSpace(className)) className = "MyForgeBehavior";
            if (string.IsNullOrWhiteSpace(ns)) ns = "MyMod.CampaignBehaviors";
            // Enforce safety: no class named "Campaign"
            className = className.Replace("Campaign", "CampaignBehaviors");

            var sb = new StringBuilder();
            sb.AppendLine("// ═══════════════════════════════════════════════════════════════");
            sb.AppendLine("// CALRADIA FORGE — CampaignBehaviorBase Scaffold");
            sb.AppendLine("// ─── Generated by ForgeNoviceHub. Safe to copy to your project.");
            sb.AppendLine("// ═══════════════════════════════════════════════════════════════");
            sb.AppendLine();
            sb.AppendLine("// STEP 1: Add these usings at the top of your file.");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using CalradiaForge.Sdk;");
            sb.AppendLine("using TaleWorlds.CampaignSystem;");
            sb.AppendLine("using TaleWorlds.CampaignSystem.Actions;");
            sb.AppendLine("using TaleWorlds.CampaignSystem.Party;");
            sb.AppendLine("using TaleWorlds.CampaignSystem.Settlements;");
            sb.AppendLine("using TaleWorlds.ObjectSystem;");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            sb.AppendLine($"    // STEP 2: Inherit from CampaignBehaviorBase.");
            sb.AppendLine($"    // This gives your class access to game events.");
            sb.AppendLine($"    public class {className} : CampaignBehaviorBase");
            sb.AppendLine("    {");
            sb.AppendLine("        // ── PERSISTENT STATE ──────────────────────────────────────");
            sb.AppendLine("        // Only store primitive types (int, float, bool, string) or");
            sb.AppendLine("        // Dictionary<string, int> keyed by Hero.StringId.");
            sb.AppendLine("        // NEVER store Hero, Settlement, or MobileParty instances directly.");
            sb.AppendLine("        private int _myCounter = 0;");
            sb.AppendLine("        private Dictionary<string, int> _heroData = new Dictionary<string, int>();");
            sb.AppendLine();
            sb.AppendLine("        // ── STEP 3: REGISTER EVENTS ───────────────────────────────");
            sb.AppendLine("        // Override RegisterEvents() to subscribe to game events.");
            sb.AppendLine("        // Always use AddNonSerializedListener — never AddSerializedListener.");
            sb.AppendLine("        public override void RegisterEvents()");
            sb.AppendLine("        {");
            sb.AppendLine("            CampaignEvents.HourlyTickEvent.AddNonSerializedListener(this, OnHourlyTick);");
            sb.AppendLine("            CampaignEvents.DailyTickSettlementEvent.AddNonSerializedListener(this, OnDailyTickSettlement);");
            sb.AppendLine("            CampaignEvents.OnSessionLaunchedEvent.AddNonSerializedListener(this, OnSessionLaunched);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        // ── STEP 4: SYNC DATA (Save / Load) ──────────────────────");
            sb.AppendLine("        // SyncData is called both when SAVING and LOADING a campaign.");
            sb.AppendLine("        // Use unique string IDs per field (they must never change between versions).");
            sb.AppendLine("        public override void SyncData(IDataStore dataStore)");
            sb.AppendLine("        {");
            sb.AppendLine("            dataStore.SyncData(\"MyMod_MyCounter\", ref _myCounter);");
            sb.AppendLine("            dataStore.SyncData(\"MyMod_HeroData\", ref _heroData);");
            sb.AppendLine();
            sb.AppendLine("            // Null-safe guard: if we just loaded, ensure collections exist.");
            sb.AppendLine("            if (dataStore.IsLoading)");
            sb.AppendLine("            {");
            sb.AppendLine("                _heroData ??= new Dictionary<string, int>();");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        // ── STEP 5: EVENT HANDLERS ────────────────────────────────");
            sb.AppendLine("        // OnSessionLaunched fires when the player loads a campaign.");
            sb.AppendLine("        // Use it to register dialogues and menus (not events — that's RegisterEvents).");
            sb.AppendLine("        private void OnSessionLaunched(CampaignGameStarter starter)");
            sb.AppendLine("        {");
            sb.AppendLine("            // Example: starter.AddPlayerLine(\"my_line\", \"start\", \"my_response\", \"Hello!\", null, null);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        // HourlyTickEvent fires every in-game hour.");
            sb.AppendLine("        // Spread optional batch work across 24 in-game hours using Forge's stable StringId hash.");
            sb.AppendLine("        private void OnHourlyTick()");
            sb.AppendLine("        {");
            sb.AppendLine("            _myCounter++;");
            sb.AppendLine("            // Stable-ID buckets select eligible optional work; bucket sizes vary and this loop still visits every settlement.");
            sb.AppendLine("            int currentHour = (int)CampaignTime.Now.ToHours;");
            sb.AppendLine("            foreach (Settlement s in Settlement.All)");
            sb.AppendLine("            {");
            sb.AppendLine("                if (!s.IsTown) continue;");
            sb.AppendLine("                if (!ForgeTimeSlicer.ShouldProcess(s.StringId, currentHour)) continue;");
            sb.AppendLine("                // TODO: process this settlement here");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        // DailyTickSettlementEvent fires once per in-game day for each settlement.");
            sb.AppendLine("        private void OnDailyTickSettlement(Settlement settlement)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (settlement == null || !settlement.IsTown) return;");
            sb.AppendLine("            // TODO: your daily settlement logic here");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("// ── HOW TO REGISTER IN SubModule.cs ──────────────────────────");
            sb.AppendLine("// protected override void OnGameStart(Game game, IGameStarter gameStarterObject)");
            sb.AppendLine("// {");
            sb.AppendLine("//     base.OnGameStart(game, gameStarterObject);");
            sb.AppendLine("//     if (gameStarterObject is CampaignGameStarter campaignStarter)");
            sb.AppendLine("//         campaignStarter.AddBehavior(new " + className + "());");
            sb.AppendLine("// }");

            return sb.ToString();
        }

        // ─────────────────────────────────────────────────────────────────
        // 2. Troop XML Builder
        // ─────────────────────────────────────────────────────────────────

        /// <summary>
        /// Generates a valid NPCCharacters.xml snippet for a custom troop.
        /// Strictly uses valid slot names and enforces integer age.
        /// </summary>
        public static string GenerateTroopXml(string id = "mymod_soldier", string name = "Forge Soldier",
            string culture = "Culture.empire", int tier = 2)
        {
            if (string.IsNullOrWhiteSpace(id)) id = "mymod_soldier";
            if (string.IsNullOrWhiteSpace(name)) name = "Forge Soldier";
            if (string.IsNullOrWhiteSpace(culture)) culture = "Culture.empire";
            tier = Math.Max(1, Math.Min(6, tier));

            int level = 5 + (tier * 6);
            var troop = ForgeTroopBuilder.Create(id)
                .WithName(name)
                .WithAge(25)
                .WithLevel(level)
                .WithCulture(culture)
                .WithDefaultGroup("Infantry")
                .WithOccupation("Soldier")
                .AddSkill("OneHanded", 40 + tier * 20)
                .AddSkill("TwoHanded", 20 + tier * 10)
                .AddSkill("Polearm", 30 + tier * 10)
                .AddSkill("Athletics", 50 + tier * 10)
                .AddBattleEquipment("Item0", "horse_whip")
                .AddBattleEquipment("Item1", "heavy_round_shield")
                .AddBattleEquipment("Head", "open_desert_helmet")
                .AddBattleEquipment("Body", "desert_robe_over_mail")
                .AddBattleEquipment("Gloves", "mail_mitten")
                .AddBattleEquipment("Leg", "leather_boots")
                .AddCivilianEquipment("Item0", "horse_whip")
                .AddUpgradeTarget(id + "_veteran");

            var sb = new StringBuilder();
            sb.AppendLine("<!-- ═══════════════════════════════════════════════════════════════ -->");
            sb.AppendLine("<!-- CALRADIA FORGE — Custom Troop XML Template");
            sb.AppendLine("     Save as: ModuleData/NPCCharacters.xml");
            sb.AppendLine("     Register in SubModule.xml under: <XmlName id=\"NPCCharacters\" path=\"NPCCharacters\" />");
            sb.AppendLine("     ═══════════════════════════════════════════════════════════════ -->");
            sb.AppendLine("<NPCCharacters>");
            sb.AppendLine();
            sb.AppendLine("  <!-- Tier controls the generated level and combat skill values. -->");
            sb.AppendLine("  <!-- The equipment IDs below are native examples; replace them with IDs supplied by your mod. -->");
            sb.AppendLine("  <!-- The upgrade target is a reference: define the matching veteran NPCCharacter in your module. -->");
            sb.AppendLine(troop.BuildElement().ToString());
            sb.AppendLine($"</NPCCharacters>");

            return sb.ToString();
        }

        // ─────────────────────────────────────────────────────────────────
        // 3. Quest Scaffold (wraps ForgeQuestBuilder)
        // ─────────────────────────────────────────────────────────────────

        /// <summary>
        /// Generates a QuestBase C# class scaffold with the mandatory double-SetDialogs() rule enforced.
        /// </summary>
        public static string GenerateQuestScaffold(string questId = "my_custom_quest",
            string className = "MyCustomQuest", string ns = "MyMod.Quests", int saveTypeId = 2500001)
        {
            if (string.IsNullOrWhiteSpace(questId)) questId = "my_custom_quest";
            if (string.IsNullOrWhiteSpace(className)) className = "MyCustomQuest";
            if (string.IsNullOrWhiteSpace(ns)) ns = "MyMod.Quests";
            if (saveTypeId < 2500000) saveTypeId = 2500001;

            return ForgeQuestBuilder.Create(questId, className)
                .WithNamespace(ns)
                .WithTitle("My Custom Quest")
                .WithSaveableTypeId(saveTypeId)
                .AddSaveableField("int", "_rewardGold", 1)
                .AddSaveableField("string", "_targetHeroId", 2)
                .BuildCSharpCode()
                + "\n\n"
                + "// ── CRITICAL RULES ──────────────────────────────────────────────\n"
                + "// ✅ SetDialogs() is called in BOTH the constructor AND InitializeQuestOnGameLoad().\n"
                + "//    Skipping the second call makes NPCs silent after loading a save game.\n"
                + "// ✅ SaveableTypeId >= 2,500,000 to prevent collisions with other mods.\n"
                + "// ✅ [SaveableField(id)] values must NEVER change between mod versions.\n"
                + "// ✅ Store hero.StringId (a string), NOT the Hero object itself.\n"
                + "//    Resolve back via: MBObjectManager.Instance.GetObject<Hero>(heroId)\n";
        }

        // ─────────────────────────────────────────────────────────────────
        // 4. Item XML Builder
        // ─────────────────────────────────────────────────────────────────

        /// <summary>
        /// Generates an annotated Items.xml snippet for a custom weapon or armor.
        /// </summary>
        public static string GenerateItemXml(string id = "mymod_iron_sword", string name = "Forge Iron Sword",
            string culture = "Culture.empire", string itemType = "OneHandedWeapon")
        {
            if (string.IsNullOrWhiteSpace(id)) id = "mymod_iron_sword";
            if (string.IsNullOrWhiteSpace(name)) name = "Forge Iron Sword";
            if (string.IsNullOrWhiteSpace(culture)) culture = "Culture.empire";
            if (string.IsNullOrWhiteSpace(itemType)) itemType = "OneHandedWeapon";

            var item = ForgeItemBuilder.Create(id)
                .WithName(name)
                .WithCulture(culture)
                .WithType(itemType);

            ConfigureNoviceItem(item, itemType);
            var itemElement = item.BuildElement();
            ConfigureNoviceItemElement(itemElement, itemType);
            if (itemElement.Element("ItemComponent")?.Element("Weapon") != null &&
                itemElement.Attribute("body_name") == null)
            {
                itemElement.SetAttributeValue("body_name", "bo_sword_2h_a");
                itemElement.SetAttributeValue("holster_mesh", "sword_2h_a");
            }
            itemElement.SetAttributeValue("is_merchandise", "true");

            var sb = new StringBuilder();
            sb.AppendLine("<!-- ═══════════════════════════════════════════════════════════════ -->");
            sb.AppendLine("<!-- CALRADIA FORGE — Custom Item XML Template");
            sb.AppendLine("     Save as: ModuleData/Items.xml");
            sb.AppendLine("     Register in SubModule.xml: <XmlName id=\"Items\" path=\"Items\" />");
            sb.AppendLine("     ID prefix rule: use your mod prefix to avoid overwriting vanilla items.");
            sb.AppendLine("     Replace mesh/body names with assets shipped by your module before release.");
            sb.AppendLine("     ═══════════════════════════════════════════════════════════════ -->");
            sb.AppendLine("<Items>");
            sb.AppendLine();
            sb.AppendLine(itemElement.ToString());
            sb.AppendLine($"</Items>");
            return sb.ToString();
        }

        private static void ConfigureNoviceItem(ForgeItemBuilder item, string itemType)
        {
            switch (itemType.ToUpperInvariant())
            {
                case "ONEHANDEDWEAPON":
                    item.WithValue(500).WithWeight(1.5).AsWeapon("OneHandedSword", 90, 88, 18, "Pierce", 28, "Cut", "onehanded_block_shield_swing");
                    break;
                case "TWOHANDEDWEAPON":
                    item.WithValue(500).WithWeight(2.5).AsWeapon("TwoHandedSword", 85, 82, 22, "Pierce", 35, "Cut", "twohanded_block_swing");
                    break;
                case "POLEARM":
                    item.WithValue(500).WithWeight(2.0).AsWeapon("TwoHandedPolearm", 56, 70, 12, "Pierce", 24, "Cut", "polearm_block_thrust");
                    break;
                case "BOW":
                    item.WithMesh("shortbow_b").WithValue(500).WithWeight(0.3)
                        .AsWeapon("Bow", 92, 87, 30, "Pierce", 0, "Blunt", "bow");
                    break;
                case "CROSSBOW":
                    item.WithMesh("crossbow_a").WithValue(500).WithWeight(1.0)
                        .AsWeapon("Crossbow", 92, 62, 75, "Pierce", 0, "Blunt", "crossbow_fast");
                    break;
                case "THROWN":
                    item.WithValue(200).WithWeight(1.0).AsWeapon("ThrowingAxe", 70, 70, 35, "Pierce", 35, "Cut", "throwing_axe");
                    break;
                case "SHIELD":
                    item.WithMesh("sturgia_shield_a").WithValue(200).WithWeight(4.7)
                        .AsWeapon("LargeShield", 86, 86, 5, "Blunt", 0, "Blunt", "hand_shield");
                    break;
                case "HORSE":
                    item.WithValue(2000).WithWeight(50.0).AsHorse(45, 65, 15, 20);
                    break;
                case "HEADARMOR":
                    item.WithMesh("headscarf_d").WithValue(75).WithWeight(0.5).AsArmor(0, 0, 0, 3, false);
                    break;
                case "BODYARMOR":
                    item.WithMesh("aserai_tunic_long").WithValue(200).WithWeight(1.6).AsArmor(2, 2, 1, 0, true);
                    break;
                case "LEGARMOR":
                    item.WithMesh("aserai_female_costume_shoe").WithValue(50).WithWeight(0.5).AsArmor(0, 2, 0, 0, false);
                    break;
                case "HANDARMOR":
                    item.WithMesh("padded_vambrace_a_handguard").WithValue(100).WithWeight(0.6).AsArmor(0, 0, 9, 0, false);
                    break;
                case "CAPE":
                    item.WithMesh("aserai_female_costume_cloak").WithValue(50).WithWeight(0.2).AsArmor(2, 0, 0, 0, false);
                    break;
                case "HORSEHARNESS":
                    item.WithMesh("bandit_saddle_desert").WithValue(500).WithWeight(21.0).AsArmor(9, 0, 0, 0, false);
                    break;
                case "GOODS":
                    item.WithValue(100).WithWeight(1.0);
                    break;
                default:
                    throw new ArgumentException("Unsupported Bannerlord item type.", nameof(itemType));
            }
        }

        private static void ConfigureNoviceItemElement(XElement item, string itemType)
        {
            string normalizedType = itemType.ToUpperInvariant();
            var component = item.Element("ItemComponent");
            var weapon = component?.Element("Weapon");
            var armor = component?.Element("Armor");

            switch (normalizedType)
            {
                case "BOW":
                    item.SetAttributeValue("body_name", "bo_shortbow_b");
                    item.SetAttributeValue("difficulty", "0");
                    item.SetAttributeValue("holster_mesh", "shortbow_b_holster");
                    item.SetAttributeValue("holster_mesh_with_weapon", "shortbow_b_holster_weapon");
                    item.SetAttributeValue("item_holsters", "bow_hip:bow_hip_2");
                    weapon.SetAttributeValue("ammo_class", "Arrow");
                    weapon.SetAttributeValue("ammo_limit", "1");
                    weapon.SetAttributeValue("missile_speed", "84");
                    weapon.SetAttributeValue("weapon_length", "106");
                    weapon.SetAttributeValue("accuracy", "99");
                    weapon.SetAttributeValue("physics_material", "wood_weapon");
                    weapon.SetAttributeValue("center_of_mass", "0.0,0,-0.1");
                    weapon.Attribute("weapon_balance")?.Remove();
                    weapon.Attribute("swing_damage")?.Remove();
                    weapon.Attribute("swing_damage_type")?.Remove();
                    SetNoviceWeaponFlags(weapon, "RangedWeapon", "HasString", "StringHeldByHand", "NotUsableWithOneHand", "TwoHandIdleOnMount", "AutoReload", "UnloadWhenSheathed", "CanBeUsedWhileCrouched");
                    SetNoviceItemFlags(item, "Stealth", "ForceAttachOffHandPrimaryItemBone");
                    break;
                case "CROSSBOW":
                    item.SetAttributeValue("body_name", "bo_cross_bow_heavy");
                    item.SetAttributeValue("difficulty", "0");
                    item.SetAttributeValue("AmmoOffset", "0.0, 0.02131, 0.24650");
                    item.SetAttributeValue("item_holsters", "crossbow_back:bow_hip:mace_right_hip:bow_hip_2");
                    item.SetAttributeValue("holster_position_shift", "0.02,0,-0.4");
                    weapon.SetAttributeValue("ammo_class", "Bolt");
                    weapon.SetAttributeValue("ammo_limit", "1");
                    weapon.SetAttributeValue("missile_speed", "77");
                    weapon.SetAttributeValue("accuracy", "95");
                    weapon.SetAttributeValue("weapon_length", "95");
                    weapon.SetAttributeValue("reload_phase_count", "2");
                    weapon.SetAttributeValue("physics_material", "wood_weapon");
                    weapon.SetAttributeValue("center_of_mass", "0,0,0.4");
                    weapon.Attribute("weapon_balance")?.Remove();
                    weapon.Attribute("swing_damage")?.Remove();
                    weapon.Attribute("swing_damage_type")?.Remove();
                    SetNoviceWeaponFlags(weapon, "RangedWeapon", "HasString", "NotUsableWithOneHand", "TwoHandIdleOnMount");
                    SetNoviceItemFlags(item, "Stealth");
                    break;
                case "SHIELD":
                    item.SetAttributeValue("body_name", "bo_cap_sturgia_shield_a");
                    item.SetAttributeValue("shield_body_name", "bo_sturgia_shield_a");
                    item.SetAttributeValue("recalculate_body", "false");
                    item.SetAttributeValue("using_tableau", "true");
                    item.SetAttributeValue("difficulty", "0");
                    item.SetAttributeValue("item_holsters", "shield_round:shield_4");
                    item.SetAttributeValue("has_lower_holster_priority", "true");
                    item.SetAttributeValue("holster_position_shift", "0,0,0");
                    weapon.SetAttributeValue("body_armor", "9");
                    weapon.SetAttributeValue("physics_material", "wood_shield");
                    weapon.SetAttributeValue("position", "-0.02, 0.0, 0.0");
                    weapon.SetAttributeValue("rotation", "-15.0,-90.0,-10.0");
                    weapon.SetAttributeValue("weapon_length", "70");
                    weapon.SetAttributeValue("center_of_mass", "0, 0, 0");
                    weapon.SetAttributeValue("hit_points", "500");
                    weapon.SetAttributeValue("modifier_group", "shield");
                    weapon.Attribute("weapon_balance")?.Remove();
                    weapon.Attribute("swing_damage")?.Remove();
                    weapon.Attribute("swing_damage_type")?.Remove();
                    SetNoviceWeaponFlags(weapon, "CanBlockRanged", "HasHitPoints");
                    SetNoviceItemFlags(item, "WoodenParry", "ForceAttachOffHandPrimaryItemBone", "HeldInOffHand");
                    break;
                case "HEADARMOR":
                    ConfigureNoviceArmor(armor, "head_armor", "3");
                    armor.SetAttributeValue("has_gender_variations", "false");
                    armor.SetAttributeValue("hair_cover_type", "all");
                    armor.SetAttributeValue("modifier_group", "cloth_unarmoured");
                    armor.SetAttributeValue("material_type", "Cloth");
                    armor.SetAttributeValue("beard_cover_type", "type3");
                    SetNoviceItemFlags(item, "Stealth", "Civilian", "UseTeamColor");
                    break;
                case "BODYARMOR":
                    ConfigureNoviceArmor(armor, "body_armor", "2", "leg_armor", "2", "arm_armor", "1");
                    armor.SetAttributeValue("has_gender_variations", "true");
                    armor.SetAttributeValue("covers_body", "true");
                    armor.SetAttributeValue("modifier_group", "cloth_unarmoured");
                    armor.SetAttributeValue("material_type", "Cloth");
                    SetNoviceItemFlags(item, "UseTeamColor", "Civilian");
                    break;
                case "LEGARMOR":
                    ConfigureNoviceArmor(armor, "leg_armor", "2");
                    armor.Attribute("has_gender_variations")?.Remove();
                    armor.SetAttributeValue("covers_legs", "false");
                    armor.SetAttributeValue("modifier_group", "cloth_unarmoured");
                    armor.SetAttributeValue("material_type", "Cloth");
                    SetNoviceItemFlags(item, "Civilian");
                    break;
                case "HANDARMOR":
                    ConfigureNoviceArmor(armor, "arm_armor", "9");
                    armor.Attribute("has_gender_variations")?.Remove();
                    armor.SetAttributeValue("stealth_factor", "10");
                    armor.SetAttributeValue("modifier_group", "cloth");
                    armor.SetAttributeValue("material_type", "Cloth");
                    SetNoviceItemFlags(item, "Stealth", "Civilian");
                    break;
                case "CAPE":
                    ConfigureNoviceArmor(armor, "body_armor", "2");
                    armor.Attribute("has_gender_variations")?.Remove();
                    armor.SetAttributeValue("modifier_group", "cloth_unarmoured");
                    armor.SetAttributeValue("material_type", "Cloth");
                    SetNoviceItemFlags(item, "Civilian", "UseTeamColor");
                    break;
                case "HORSEHARNESS":
                    item.SetAttributeValue("subtype", "body_armor");
                    ConfigureNoviceArmor(armor, "body_armor", "9");
                    armor.Attribute("has_gender_variations")?.Remove();
                    armor.SetAttributeValue("mane_cover_type", "none");
                    armor.SetAttributeValue("family_type", "1");
                    armor.SetAttributeValue("reins_mesh", "bandit_saddle_desert_rein");
                    armor.SetAttributeValue("material_type", "Cloth");
                    SetNoviceItemFlags(item, "Civilian");
                    break;
            }
        }

        private static void ConfigureNoviceArmor(XElement armor, params string[] attributes)
        {
            armor.RemoveAttributes();
            for (int index = 0; index < attributes.Length; index += 2)
                armor.SetAttributeValue(attributes[index], attributes[index + 1]);
        }

        private static void SetNoviceWeaponFlags(XElement weapon, params string[] flags)
        {
            var weaponFlags = new XElement("WeaponFlags");
            foreach (string flag in flags)
                weaponFlags.SetAttributeValue(flag, "true");
            weapon.Add(weaponFlags);
        }

        private static void SetNoviceItemFlags(XElement item, params string[] flags)
        {
            var itemFlags = item.Element("Flags");
            if (itemFlags == null)
            {
                itemFlags = new XElement("Flags");
                item.Add(itemFlags);
            }

            foreach (string flag in flags)
                itemFlags.SetAttributeValue(flag, "true");
        }

        // ─────────────────────────────────────────────────────────────────
        // 5. SubModule.xml Generator
        // ─────────────────────────────────────────────────────────────────

        /// <summary>
        /// Generates a complete and valid SubModule.xml for a new mod.
        /// </summary>
        public static string GenerateSubModuleXml(string modId = "MyNewMod", string dllName = "MyNewMod",
            string version = "1.0.0", string subModuleClass = "MyNewMod.SubModule")
        {
            if (string.IsNullOrWhiteSpace(modId)) modId = "MyNewMod";
            if (string.IsNullOrWhiteSpace(dllName)) dllName = "MyNewMod";
            if (string.IsNullOrWhiteSpace(version)) version = "1.0.0";
            if (string.IsNullOrWhiteSpace(subModuleClass)) subModuleClass = "MyNewMod.SubModule";

            var sb = new StringBuilder();
            sb.AppendLine("<!-- ═══════════════════════════════════════════════════════════════ -->");
            sb.AppendLine("<!-- CALRADIA FORGE — SubModule.xml Template");
            sb.AppendLine("     CRITICAL: The folder name 'Modules/<YourModId>' MUST match <Id value>.");
            sb.AppendLine("     CRITICAL: DLLName must exactly match the compiled DLL filename.");
            sb.AppendLine("     ═══════════════════════════════════════════════════════════════ -->");
            sb.AppendLine("<Module>");
            sb.AppendLine();
            sb.AppendLine($"  <!-- Mod identification -->");
            sb.AppendLine($"  <Name value=\"{modId}\"/>");
            sb.AppendLine($"  <Id value=\"{modId}\"/>               <!-- Must match folder name: Modules/{modId}/ -->");
            sb.AppendLine($"  <Version value=\"v{version}\"/>");
            sb.AppendLine($"  <SingleplayerModule value=\"true\"/>");
            sb.AppendLine($"  <MultiplayerModule value=\"false\"/>");
            sb.AppendLine($"  <Official value=\"false\"/>            <!-- NEVER set to true for mods -->");
            sb.AppendLine();
            sb.AppendLine($"  <!-- Dependencies: list every module this mod needs to load first -->");
            sb.AppendLine($"  <DependedModules>");
            sb.AppendLine($"    <DependedModule Id=\"Native\"/>       <!-- Always required -->");
            sb.AppendLine($"    <DependedModule Id=\"SandBoxCore\"/>  <!-- Required for campaign -->");
            sb.AppendLine($"    <DependedModule Id=\"SandBox\"/>      <!-- NPC dialogues, quests -->");
            sb.AppendLine($"    <DependedModule Id=\"StoryMode\"/>    <!-- Story quests framework -->");
            sb.AppendLine($"  </DependedModules>");
            sb.AppendLine();
            sb.AppendLine($"  <!-- C# assemblies loaded by the engine -->");
            sb.AppendLine($"  <SubModules>");
            sb.AppendLine($"    <SubModule>");
            sb.AppendLine($"      <Name value=\"{modId}\"/>");
            sb.AppendLine($"      <DLLName value=\"{dllName}.dll\"/>  <!-- In bin/Win64_Shipping_Client/ -->");
            sb.AppendLine($"      <SubModuleClassType value=\"{subModuleClass}\"/>  <!-- Fully qualified name -->");
            sb.AppendLine($"      <Assemblies/>");
            sb.AppendLine($"    </SubModule>");
            sb.AppendLine($"  </SubModules>");
            sb.AppendLine();
            sb.AppendLine($"  <!-- XML data files in ModuleData/ (omit .xml extension in path) -->");
            sb.AppendLine($"  <Xmls>");
            sb.AppendLine($"    <!-- <XmlNode> <XmlName id=\"Items\" path=\"items_mymod\"/> </XmlNode> -->");
            sb.AppendLine($"    <!-- <XmlNode> <XmlName id=\"NPCCharacters\" path=\"troops_mymod\"/> </XmlNode> -->");
            sb.AppendLine($"    <!-- <XmlNode> <XmlName id=\"SPCultures\" path=\"cultures_mymod\"/> </XmlNode> -->");
            sb.AppendLine($"  </Xmls>");
            sb.AppendLine();
            sb.AppendLine($"</Module>");
            return sb.ToString();
        }

        // ─────────────────────────────────────────────────────────────────
        // 6. Mod Readiness Checklist
        // ─────────────────────────────────────────────────────────────────

        /// <summary>
        /// Inspects a mod folder (by path or mod ID hint) and produces a readiness checklist.
        /// When modPath is empty, returns a universal checklist with explanations.
        /// </summary>
        public static string GenerateModChecklist(string modPathOrHint = "")
        {
            var sb = new StringBuilder();
            sb.AppendLine("╔═══════════════════════════════════════════════════════════╗");
            sb.AppendLine("║  CALRADIA FORGE — Mod Readiness Checklist                ║");
            sb.AppendLine("╚═══════════════════════════════════════════════════════════╝");
            sb.AppendLine();
            sb.AppendLine("✦ FOLDER STRUCTURE");
            sb.AppendLine("  ☐ Modules/<YourModId>/               ← Root module folder");
            sb.AppendLine("  ☐ Modules/<YourModId>/SubModule.xml  ← Manifest (required)");
            sb.AppendLine("  ☐ Modules/<YourModId>/bin/Win64_Shipping_Client/<ModId>.dll");
            sb.AppendLine("  ☐ Modules/<YourModId>/ModuleData/    ← XML data files");
            sb.AppendLine("  ☐ Folder name EXACTLY matches <Id value> in SubModule.xml");
            sb.AppendLine();
            sb.AppendLine("✦ SUBMODULE.XML SANITY");
            sb.AppendLine("  ☐ <Id value> matches Modules/<YourModId> folder name");
            sb.AppendLine("  ☐ <DLLName value> matches compiled .dll filename exactly");
            sb.AppendLine("  ☐ <SubModuleClassType> is the fully-qualified namespace.class");
            sb.AppendLine("  ☐ <Official value=\"false\"/> — never set to true");
            sb.AppendLine("  ☐ All dependencies listed in <DependedModules>");
            sb.AppendLine();
            sb.AppendLine("✦ C# CODE SAFETY");
            sb.AppendLine("  ☐ No class/namespace/folder named 'Campaign'");
            sb.AppendLine("    (shadows TaleWorlds.CampaignSystem.Campaign.Current)");
            sb.AppendLine("  ☐ SyncData stores only primitives, not Hero/Settlement objects");
            sb.AppendLine("  ☐ SaveableTypeDefiner base ID >= 2,500,000");
            sb.AppendLine("  ☐ [SaveableField] IDs never changed between versions");
            sb.AppendLine("  ☐ SetDialogs() called in BOTH constructor AND InitializeQuestOnGameLoad()");
            sb.AppendLine("  ☐ AddNonSerializedListener used (never AddSerializedListener)");
            sb.AppendLine();
            sb.AppendLine("✦ XML DATA FILES");
            sb.AppendLine("  ☐ Each XML registered in SubModule.xml <Xmls> section");
            sb.AppendLine("  ☐ Custom item/troop IDs have a unique mod prefix (e.g. mymod_sword_1)");
            sb.AppendLine("  ☐ NPCCharacter age is an integer (0–128), not a float");
            sb.AppendLine("  ☐ Equipment slot names are valid: Item0, Item1, Item2, Item3,");
            sb.AppendLine("    Head, Cape, Body, Gloves, Leg, Horse, HorseHarness");
            sb.AppendLine("  ☐ Upgrade target IDs exist in the same or a loaded NPCCharacters.xml");
            sb.AppendLine();
            sb.AppendLine("✦ AUDIO (if applicable)");
            sb.AppendLine("  ☐ Audio files in Modules/<Id>/ModuleSounds/ (.ogg or .wav)");
            sb.AppendLine("  ☐ Declared in ModuleData/module_sounds.xml");
            sb.AppendLine("  ☐ sound_category is one of: ui, mission_combat, ambient, voice");
            sb.AppendLine("  ☐ Registered in SubModule.xml under <XmlName id=\"Sounds\"/>");
            sb.AppendLine();
            sb.AppendLine("✦ DISTRIBUTION SAFETY");
            sb.AppendLine("  ☐ Assembly has Company, Product, Description, Copyright metadata");
            sb.AppendLine("  ☐ No .bat or .ps1 scripts in the distribution ZIP");
            sb.AppendLine("  ☐ ZIP does not include bin/obj build artifacts");
            sb.AppendLine();
            sb.AppendLine("✦ IN-GAME TEST");
            sb.AppendLine("  ☐ Mod appears in launcher without error");
            sb.AppendLine("  ☐ New game loads without crash");
            sb.AppendLine("  ☐ Save and reload works (SyncData verified)");
            sb.AppendLine("  ☐ No error in game log for your mod's namespace");

            // If a path hint was given, add a dynamic note
            if (!string.IsNullOrWhiteSpace(modPathOrHint))
            {
                sb.AppendLine();
                sb.AppendLine($"── Mod hint provided: \"{modPathOrHint}\"");
                sb.AppendLine("   Use the Rule Compliance Auditor (rule-auditor) with this ID");
                sb.AppendLine("   to run an automated structural scan on the actual module folder.");
            }

            return sb.ToString();
        }

        // ─────────────────────────────────────────────────────────────────
        // 7. CampaignEvent Explainer
        // ─────────────────────────────────────────────────────────────────

        /// <summary>
        /// Returns an explanation of when a CampaignEvent fires and what to do with it.
        /// If eventName is empty, returns the full catalog of supported events.
        /// </summary>
        static readonly Dictionary<string, string> CampaignEventCatalog = CreateCampaignEventCatalog();

        static Dictionary<string, string> CreateCampaignEventCatalog() => new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["OnSessionLaunchedEvent"] =
                "Fires when a campaign session starts (new game or loaded save).\n" +
                "USE FOR: Registering custom dialogues, menu options, and initial setup.\n" +
                "PARAMETER: CampaignGameStarter starter — call starter.AddPlayerLine() / AddBehavior() here.",
            ["HourlyTickEvent"] =
                "Fires every in-game hour (24 times per in-game day).\n" +
                "USE FOR: Slow background processing — economy updates, NPC state machines.\n" +
                "TIP: For optional work whose deferral preserves behavior, use ForgeTimeSlicer.ShouldProcess(settlement.StringId, currentHour); stable-ID bucket sizes may vary, and a loop still scans every settlement (O(N)).",
            ["DailyTickSettlementEvent"] =
                "Fires once per in-game day for EACH settlement.\n" +
                "USE FOR: Settlement loyalty, food, economy adjustments.\n" +
                "PARAMETER: Settlement settlement — always check settlement.IsTown before modifying.",
            ["DailyTickPartyEvent"] =
                "Fires once per in-game day for EACH mobile party on the map.\n" +
                "USE FOR: AI behavior tweaks, troop morale, custom party mechanics.\n" +
                "PARAMETER: MobileParty mobileParty — check mobileParty.IsActive before modifying.",
            ["OnHeroKilledEvent"] =
                "Fires when any hero (player or NPC) dies in battle or by other causes.\n" +
                "USE FOR: Custom death consequences, faction power shifts, successor events.\n" +
                "PARAMETERS: Hero victim, Hero killer, KillCharacterAction.KillCharacterActionDetail detail",
            ["OnHeroCreatedEvent"] =
                "Fires when a new hero is created (companions hired, children born, etc.).\n" +
                "USE FOR: Assigning custom traits, skills, or backstory to new heroes.\n" +
                "PARAMETER: Hero hero, bool isBornNaturally",
            ["OnCharacterCreatedEvent"] =
                "Fires at player character creation in the intro sequence.\n" +
                "USE FOR: Registering starting buffs, custom starting items, or tutorial flags.",
            ["OnSettlementOwnerChangedEvent"] =
                "Fires when a settlement (town/castle) changes ownership (siege victory).\n" +
                "USE FOR: Triggering custom loot distribution, NPC reactions, or reputation changes.\n" +
                "PARAMETERS: Settlement settlement, bool openToClaim, Hero newOwner, Hero previousOwner, Hero capturingHero, ChangeOwnerOfSettlementAction.ChangeOwnerOfSettlementDetail detail",
            ["OnTroopRecruitedEvent"] =
                "Fires when the player or any party recruits troops from a settlement or prisoner stack.\n" +
                "USE FOR: Tracking recruitment stats, custom bonuses on recruitment.\n" +
                "PARAMETERS: Hero recruiterHero, Settlement sourceSettlement, Hero recruitmentSource, CharacterObject troop, int count",
            ["BattleEndedEvent"] =
                "Fires after any battle (field, siege, hideout) concludes.\n" +
                "USE FOR: Battle aftermath rewards, stat tracking, or custom loot distribution.\n" +
                "PARAMETER: MapEvent mapEvent — check mapEvent.WinningSide for outcome.",
            ["OnSiegeEventStartedEvent"] =
                "Fires when a siege begins against a settlement.\n" +
                "USE FOR: Custom siege preparations, AI reinforcement orders, garrison bonuses.\n" +
                "PARAMETER: SiegeEvent siegeEvent",
            ["OnQuestStartedEvent"] =
                "Fires when any quest (vanilla or custom) begins.\n" +
                "USE FOR: Cross-quest interaction, quest tracking, or narrative triggers.\n" +
                "PARAMETER: QuestBase quest",
            ["OnQuestCompletedEvent"] =
                "Fires when any quest is completed (success or failure).\n" +
                "USE FOR: Follow-up events, relationship changes, or follow-on quest triggers.\n" +
                "PARAMETERS: QuestBase quest, QuestBase.QuestCompleteDetails detail",
            ["MakePeace"] =
                "Fires when two kingdoms sign a peace treaty.\n" +
                "USE FOR: Post-war recovery events, trade route restoration.\n" +
                "PARAMETERS: IFaction faction1, IFaction faction2, MakePeaceAction.MakePeaceDetail detail",
            ["WarDeclared"] =
                "Fires when two kingdoms declare war.\n" +
                "USE FOR: Mobilization triggers, faction AI overrides.\n" +
                "PARAMETERS: IFaction faction1, IFaction faction2, DeclareWarAction.DeclareWarDetail detail",
            ["OnClanChangedKingdomEvent"] =
                "Fires when a clan joins or leaves a kingdom.\n" +
                "USE FOR: Vassal tracking, custom loyalty penalties, coalition building.\n" +
                "PARAMETERS: Clan clan, Kingdom oldKingdom, Kingdom newKingdom, ChangeKingdomAction.ChangeKingdomActionDetail detail, bool showNotification",
            ["OnHeroLevelledUpEvent"] =
                "Fires each time a hero gains a character level.\n" +
                "USE FOR: Custom level-up rewards, perks, or story triggers.\n" +
                "PARAMETERS: Hero hero, bool shouldNotify",
            ["OnSkillLevelledUpEvent"] =
                "Fires when a hero's skill increases by any amount.\n" +
                "USE FOR: Tracking mastery milestones, granting bonuses at skill thresholds.\n" +
                "PARAMETERS: Hero hero, SkillObject skill, int xpChange, int levelChange",
            ["OnMarriageEvent"] =
                "Fires when two heroes marry.\n" +
                "USE FOR: Dynastic bonuses, spouse trait inheritance, custom narrative events.\n" +
                "PARAMETERS: Hero firstHero, Hero secondHero",
            ["OnChildBornEvent"] =
                "Fires when a child is born to two heroes.\n" +
                "USE FOR: Heir tracking, custom naming ceremonies, custom trait assignment.\n" +
                "PARAMETERS: Hero mother, Hero child",
            ["OnItemsDiscardedByHeroEvent"] =
                "Fires when a hero discards or sells items from inventory.\n" +
                "USE FOR: Scavenging mechanics, faction asset tracking.\n" +
                "PARAMETER: Hero hero",
            ["OnGameLoadedEvent"] =
                "Fires after all SyncData is restored and the session is playable.\n" +
                "USE FOR: Post-load validation, migrating old save data to new formats.\n" +
                "PARAMETER: CampaignGameStarter gameStarter",
            ["OnAfterSessionLaunchedEvent"] =
                "Fires AFTER OnSessionLaunchedEvent — the game world is fully initialized.\n" +
                "USE FOR: Querying existing heroes, settlements, or parties that weren't available earlier.\n" +
                "PARAMETER: CampaignGameStarter gameStarter",
            ["OnNewGameCreatedEvent"] =
                "Fires when a brand-new game is started (not loaded from save).\n" +
                "USE FOR: Starting bonuses, initial faction states, custom world initialization.\n" +
                "PARAMETER: CampaignGameStarter gameStarter",
            ["VillageBeingRaided"] =
                "Fires when a hostile party begins raiding a village.\n" +
                "USE FOR: Refugee mechanics, custom militia spawning, hunger events.\n" +
                "PARAMETER: Village village",
            ["OnVillageLooted"] =
                "Fires after a village has been looted by a hostile party.\n" +
                "USE FOR: Post-raid recovery mechanics, tracking prosperity loss.\n" +
                "PARAMETER: Village village",
            ["OnRebelliousClanDisbandedAtSettlement"] =
                "Fires when a rebellious clan disbands at a settlement (failed rebellion).\n" +
                "USE FOR: Stability bonuses, survivor tracking.\n" +
                "PARAMETERS: Settlement settlement, Clan clan"
        };

        public static string ExplainCampaignEvent(string eventName = "")
        {
            var catalog = CampaignEventCatalog;

            if (string.IsNullOrWhiteSpace(eventName) || eventName.Trim().ToLowerInvariant() == "all")
            {
                // Return full catalog
                var sb = new StringBuilder();
                sb.AppendLine("╔═══════════════════════════════════════════════════════════╗");
                sb.AppendLine("║  CALRADIA FORGE — CampaignEvent Catalog                  ║");
                sb.AppendLine("║  Usage: Type an event name above to get its explanation. ║");
                sb.AppendLine("╚═══════════════════════════════════════════════════════════╝");
                sb.AppendLine();
                int i = 1;
                foreach (var kvp in catalog)
                {
                    sb.AppendLine($"{i,2}. {kvp.Key}");
                    i++;
                }
                sb.AppendLine();
                sb.AppendLine("── HOW TO SUBSCRIBE ─────────────────────────────────────");
                sb.AppendLine("  // In RegisterEvents():");
                sb.AppendLine("  CampaignEvents.HourlyTickEvent.AddNonSerializedListener(this, OnHourlyTick);");
                sb.AppendLine("  private void OnHourlyTick() { /* your code */ }");
                return sb.ToString();
            }

            // Look up specific event
            if (catalog.TryGetValue(eventName.Trim(), out var explanation))
            {
                return $"══ {eventName} ══\n\n{explanation}\n\n"
                     + "── SUBSCRIPTION PATTERN ────────────────────────────────────\n"
                     + $"  // In RegisterEvents():\n"
                     + $"  CampaignEvents.{eventName}.AddNonSerializedListener(this, On{eventName.Replace("Event", "").Replace("On", "")});\n"
                     + $"  private void On{eventName.Replace("Event", "").Replace("On", "")}() {{ /* your code */ }}\n";
            }

            // Fuzzy: find close match
            var near = new List<string>();
            foreach (var k in catalog.Keys)
                if (k.IndexOf(eventName.Trim(), StringComparison.OrdinalIgnoreCase) >= 0)
                    near.Add(k);

            if (near.Count > 0)
                return $"Event \"{eventName}\" not found exactly. Did you mean:\n" + string.Join("\n", near) +
                       "\n\nType the exact name to get its full explanation.";

            return $"Event \"{eventName}\" not found in the catalog. Type 'all' for the full list of {catalog.Count} supported events.";
        }

        // ─────────────────────────────────────────────────────────────────
        // 8. Gauntlet Hint & Tooltip Scaffold
        // ─────────────────────────────────────────────────────────────────

        /// <summary>
        /// Generates a complete Gauntlet UI Hint binding, including C# ViewModel property with [DataSourceProperty]
        /// and the corresponding Gauntlet XML attribute syntax (Hint.HintText).
        /// </summary>
        public static string GenerateHintScaffold(string widgetType = "ButtonWidget", string title = "Recruit Volunteers", string description = "Recruit fresh recruits from the local garrison into your warband.", string shortcut = "Ctrl+Click")
        {
            if (string.IsNullOrWhiteSpace(widgetType)) widgetType = "ButtonWidget";
            if (string.IsNullOrWhiteSpace(title)) title = "Recruit Volunteers";
            if (string.IsNullOrWhiteSpace(description)) description = "Recruit fresh recruits from the local garrison into your warband.";
            if (string.IsNullOrWhiteSpace(shortcut)) shortcut = "Ctrl+Click";

            string cleanTitle = System.Text.RegularExpressions.Regex.Replace(title, @"[^a-zA-Z0-9_]", "");
            if (string.IsNullOrWhiteSpace(cleanTitle)) cleanTitle = "CustomAction";
            string propName = cleanTitle + "Hint";
            string stringId = "hint_" + cleanTitle.ToLowerInvariant();

            var builder = ForgeHintBuilder.Create(title)
                .WithDescription(description)
                .WithShortcut(shortcut)
                .WithRequirement("Minimum Gold: 150 denars", true)
                .WithRequirement("Available Party Capacity", true)
                .WithWarning("Recruits will desert if party morale drops below 20");

            var sb = new StringBuilder();
            sb.AppendLine("// ═══════════════════════════════════════════════════════════════");
            sb.AppendLine("// CALRADIA FORGE — Gauntlet Hint & Tooltip Scaffold");
            sb.AppendLine("// ─── Generated by ForgeNoviceHub. Safe to copy to your project.");
            sb.AppendLine("// ═══════════════════════════════════════════════════════════════");
            sb.AppendLine();
            sb.AppendLine("// ── ARCHITECTURE NOTICE ──────────────────────────────────────────");
            sb.AppendLine("// In Bannerlord Gauntlet XML, strictly use Hint.HintText=\"@PropertyName\"");
            sb.AppendLine("// or Hint.HintText=\"{=string_id}Fallback Text\". Avoid custom hover widgets,");
            sb.AppendLine("// as the native hint engine delivers the rich dark-parchment aesthetic.");
            sb.AppendLine();
            sb.AppendLine("// ── PART 1: C# VIEWMODEL PROPERTY ────────────────────────────────");
            sb.AppendLine("// Paste this inside your ViewModel class inheriting from TaleWorlds.Library.ViewModel:");
            sb.AppendLine(builder.BuildViewModelPropertySnippet(propName, "T"));
            sb.AppendLine();
            sb.AppendLine("// ── PART 2: GAUNTLET XML ATTRIBUTE ───────────────────────────────");
            sb.AppendLine($"// Attach this attribute to your <{widgetType}> inside GUI/Prefabs/*.xml:");
            sb.AppendLine($"<{widgetType} Command.Click=\"Execute{cleanTitle}\" {builder.BuildXmlAttribute(propName)} ... >");
            sb.AppendLine();
            sb.AppendLine("// ── PART 3: LOCALIZATION XML (OPTIONAL) ──────────────────────────");
            sb.AppendLine("// Paste this inside ModuleData/Languages/std_module_strings_xml.xml:");
            sb.AppendLine(builder.BuildLocalizationXml(stringId));
            sb.AppendLine();
            sb.AppendLine("// ── PART 4: RUNTIME PREVIEW OF THE GENERATED HINT ────────────────");
            sb.AppendLine(builder.BuildHintText());

            return sb.ToString();
        }

        // ─────────────────────────────────────────────────────────────────
        // 9. Workshop & Enterprise Scaffolder
        // ─────────────────────────────────────────────────────────────────

        /// <summary>
        /// Generates a complete custom workshop definition (workshops.xml) and accompanying C# CampaignBehaviorBase
        /// with inventory underflow prevention and dynamic market consumption.
        /// </summary>
        public static string GenerateWorkshopScaffold(string workshopType = "apothecary", string inputItem = "grain",
            string outputItem = "medicine", string className = "CustomWorkshopBehavior")
        {
            if (string.IsNullOrWhiteSpace(workshopType)) workshopType = "apothecary";
            if (string.IsNullOrWhiteSpace(inputItem)) inputItem = "grain";
            if (string.IsNullOrWhiteSpace(outputItem)) outputItem = "medicine";
            if (string.IsNullOrWhiteSpace(className)) className = "CustomWorkshopBehavior";

            var sb = new StringBuilder();
            sb.AppendLine("// ═══════════════════════════════════════════════════════════════");
            sb.AppendLine("// CALRADIA FORGE — Workshop & Enterprise Scaffolder");
            sb.AppendLine("// ─── Generated by ForgeNoviceHub. Safe to copy to your project.");
            sb.AppendLine("// ═══════════════════════════════════════════════════════════════");
            sb.AppendLine();
            sb.AppendLine("// ── PART 1: ModuleData/workshops.xml ─────────────────────────────");
            sb.AppendLine("/*");
            sb.AppendLine("<?xml version=\"1.0\" encoding=\"utf-8\"?>");
            sb.AppendLine("<Workshops>");
            sb.AppendLine($"  <WorkshopType id=\"{workshopType}\" name=\"{{={workshopType}_name}}{char.ToUpper(workshopType[0]) + workshopType.Substring(1)}\" job_name=\"{{={workshopType}_job}}{char.ToUpper(workshopType[0]) + workshopType.Substring(1)} Craftsman\">");
            sb.AppendLine("    <Productions>");
            sb.AppendLine($"      <Production conversion_speed=\"1.0\">");
            sb.AppendLine("        <Inputs>");
            sb.AppendLine($"          <Item id=\"{inputItem}\" count=\"2\"/>");
            sb.AppendLine("        </Inputs>");
            sb.AppendLine("        <Outputs>");
            sb.AppendLine($"          <Item id=\"{outputItem}\" count=\"1\"/>");
            sb.AppendLine("        </Outputs>");
            sb.AppendLine("      </Production>");
            sb.AppendLine("    </Productions>");
            sb.AppendLine("  </WorkshopType>");
            sb.AppendLine("</Workshops>");
            sb.AppendLine("*/");
            sb.AppendLine();
            sb.AppendLine("// ── PART 2: C# CampaignBehaviorBase (Production & Underflow Safety) ──");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using TaleWorlds.CampaignSystem;");
            sb.AppendLine("using TaleWorlds.CampaignSystem.Settlements;");
            sb.AppendLine("using TaleWorlds.Core;");
            sb.AppendLine();
            sb.AppendLine("namespace MyMod.CampaignBehaviors");
            sb.AppendLine("{");
            sb.AppendLine($"    public class {className} : CampaignBehaviorBase");
            sb.AppendLine("    {");
            sb.AppendLine("        private Dictionary<string, int> _dailyProductionCounts = new Dictionary<string, int>();");
            sb.AppendLine();
            sb.AppendLine("        public override void RegisterEvents()");
            sb.AppendLine("        {");
            sb.AppendLine("            CampaignEvents.DailyTickSettlementEvent.AddNonSerializedListener(this, OnDailySettlementTick);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public override void SyncData(IDataStore dataStore)");
            sb.AppendLine("        {");
            sb.AppendLine($"            dataStore.SyncData(\"{className}_Counts\", ref _dailyProductionCounts);");
            sb.AppendLine("            if (dataStore.IsLoading && _dailyProductionCounts == null)");
            sb.AppendLine("                _dailyProductionCounts = new Dictionary<string, int>();");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private void OnDailySettlementTick(Settlement settlement)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (settlement == null || !settlement.IsTown || settlement.Town == null) return;");
            sb.AppendLine();
            sb.AppendLine("            // Underflow prevention: verify town item roster has sufficient input before deducting");
            sb.AppendLine("            var roster = settlement.ItemRoster;");
            sb.AppendLine("            if (roster == null) return;");
            sb.AppendLine();
            sb.AppendLine($"            ItemObject inputObj = MBObjectManager.Instance?.GetObject<ItemObject>(\"{inputItem}\");");
            sb.AppendLine($"            ItemObject outputObj = MBObjectManager.Instance?.GetObject<ItemObject>(\"{outputItem}\");");
            sb.AppendLine("            if (inputObj == null || outputObj == null) return;");
            sb.AppendLine();
            sb.AppendLine("            int availableInput = roster.GetItemNumber(inputObj);");
            sb.AppendLine("            if (availableInput >= 2)");
            sb.AppendLine("            {");
            sb.AppendLine("                roster.AddToCounts(inputObj, -2);");
            sb.AppendLine("                roster.AddToCounts(outputObj, 1);");
            sb.AppendLine("                string sId = settlement.StringId;");
            sb.AppendLine("                _dailyProductionCounts[sId] = _dailyProductionCounts.TryGetValue(sId, out int c) ? c + 1 : 1;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        // ─────────────────────────────────────────────────────────────────
        // 10. Bandit Clan & Hideout Spawner
        // ─────────────────────────────────────────────────────────────────

        /// <summary>
        /// Generates a partyTemplates.xml snippet and a save-safe C# spawner behavior for custom bandit factions.
        /// Adheres strictly to bannerlord-party-spawner guidelines and save system GUID rules.
        /// </summary>
        public static string GenerateBanditPartyScaffold(string clanId = "mountain_raiders", string partyTemplateId = "raider_band",
            string leaderTroopId = "looter", int minTroops = 8, int maxTroops = 24)
        {
            if (string.IsNullOrWhiteSpace(clanId)) clanId = "mountain_raiders";
            if (string.IsNullOrWhiteSpace(partyTemplateId)) partyTemplateId = "raider_band";
            if (string.IsNullOrWhiteSpace(leaderTroopId)) leaderTroopId = "looter";
            minTroops = Math.Max(4, minTroops);
            maxTroops = Math.Max(minTroops, maxTroops);

            var sb = new StringBuilder();
            sb.AppendLine("// ═══════════════════════════════════════════════════════════════");
            sb.AppendLine("// CALRADIA FORGE — Bandit Clan & Hideout Spawner");
            sb.AppendLine("// ─── Generated by ForgeNoviceHub. Safe to copy to your project.");
            sb.AppendLine("// ═══════════════════════════════════════════════════════════════");
            sb.AppendLine();
            sb.AppendLine("// ── PART 1: ModuleData/partyTemplates.xml ────────────────────────");
            sb.AppendLine("/*");
            sb.AppendLine("<?xml version=\"1.0\" encoding=\"utf-8\"?>");
            sb.AppendLine("<PartyTemplates>");
            sb.AppendLine($"  <MBPartyTemplate id=\"{partyTemplateId}\">");
            sb.AppendLine("    <stacks>");
            sb.AppendLine($"      <PartyTemplateStack min_value=\"1\" max_value=\"1\" troop=\"NPCCharacter.{leaderTroopId}\"/>");
            sb.AppendLine($"      <PartyTemplateStack min_value=\"{minTroops}\" max_value=\"{maxTroops}\" troop=\"NPCCharacter.looter\"/>");
            sb.AppendLine("    </stacks>");
            sb.AppendLine("  </MBPartyTemplate>");
            sb.AppendLine("</PartyTemplates>");
            sb.AppendLine("*/");
            sb.AppendLine();
            sb.AppendLine("// ── PART 2: C# CampaignBehaviorBase (Save-Safe Programmatic Spawner) ──");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using TaleWorlds.CampaignSystem;");
            sb.AppendLine("using TaleWorlds.CampaignSystem.Party;");
            sb.AppendLine("using TaleWorlds.CampaignSystem.Party.PartyComponents;");
            sb.AppendLine("using TaleWorlds.CampaignSystem.Settlements;");
            sb.AppendLine("using TaleWorlds.Core;");
            sb.AppendLine("using TaleWorlds.Localization;");
            sb.AppendLine();
            sb.AppendLine("namespace MyMod.CampaignBehaviors");
            sb.AppendLine("{");
            sb.AppendLine("    public class BanditSpawnerBehavior : CampaignBehaviorBase");
            sb.AppendLine("    {");
            sb.AppendLine("        // Store StringIds only — never serialize raw MobileParty or Hero objects directly");
            sb.AppendLine("        private List<string> _spawnedPartyIds = new List<string>();");
            sb.AppendLine("        private int _spawnCooldownHours = 0;");
            sb.AppendLine();
            sb.AppendLine("        public override void RegisterEvents()");
            sb.AppendLine("        {");
            sb.AppendLine("            CampaignEvents.HourlyTickEvent.AddNonSerializedListener(this, OnHourlyTick);");
            sb.AppendLine("            CampaignEvents.MobilePartyDestroyed.AddNonSerializedListener(this, OnPartyDestroyed);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public override void SyncData(IDataStore dataStore)");
            sb.AppendLine("        {");
            sb.AppendLine("            dataStore.SyncData(\"BanditSpawner_Parties\", ref _spawnedPartyIds);");
            sb.AppendLine("            dataStore.SyncData(\"BanditSpawner_Cooldown\", ref _spawnCooldownHours);");
            sb.AppendLine("            if (dataStore.IsLoading && _spawnedPartyIds == null)");
            sb.AppendLine("                _spawnedPartyIds = new List<string>();");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private void OnHourlyTick()");
            sb.AppendLine("        {");
            sb.AppendLine("            if (_spawnCooldownHours > 0)");
            sb.AppendLine("            {");
            sb.AppendLine("                _spawnCooldownHours--;");
            sb.AppendLine("                return;");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            // Cap active parties to avoid performance degradation");
            sb.AppendLine("            if (_spawnedPartyIds.Count >= 5) return;");
            sb.AppendLine();
            sb.AppendLine("            Settlement target = Settlement.Find(\"hideout_forest_1\") ?? Settlement.All?[0];");
            sb.AppendLine("            if (target == null) return;");
            sb.AppendLine();
            sb.AppendLine($"            PartyTemplateObject template = MBObjectManager.Instance?.GetObject<PartyTemplateObject>(\"{partyTemplateId}\");");
            sb.AppendLine("            if (template == null) return;");
            sb.AppendLine();
            sb.AppendLine("            // Programmatic safe spawn");
            sb.AppendLine($"            TextObject name = new TextObject(\"{{=raider_name}}{char.ToUpper(clanId[0]) + clanId.Substring(1)} Warband\");");
            sb.AppendLine($"            MobileParty party = MobileParty.CreateParty(\"{clanId}_party_\" + Guid.NewGuid().ToString(\"N\").Substring(0, 8), null, null);");
            sb.AppendLine("            if (party != null)");
            sb.AppendLine("            {");
            sb.AppendLine("                party.InitializeMobilePartyAtPosition(template, target.GatePosition);");
            sb.AppendLine("                party.SetCustomName(name);");
            sb.AppendLine("                party.SetPartyUsedByQuest(true);");
            sb.AppendLine("                party.Ai.SetMovePatrolAroundSettlement(target);");
            sb.AppendLine("                _spawnedPartyIds.Add(party.StringId);");
            sb.AppendLine("                _spawnCooldownHours = 24; // 1 spawn per day cooldown");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private void OnPartyDestroyed(MobileParty destroyedParty, PartyBase destroyerParty)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (destroyedParty != null && _spawnedPartyIds.Contains(destroyedParty.StringId))");
            sb.AppendLine("            {");
            sb.AppendLine("                _spawnedPartyIds.Remove(destroyedParty.StringId);");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        // ─────────────────────────────────────────────────────────────────
        // 11. Settlement Building Architect
        // ─────────────────────────────────────────────────────────────────

        /// <summary>
        /// Generates custom settlement building definitions (buildings.xml) and a TaleWorlds GameModel Decorator
        /// applying ExplainedNumber settlement bonuses without overwriting native mechanics.
        /// </summary>
        public static string GenerateSettlementBuildingScaffold(string buildingId = "custom_granary_vault",
            string name = "Underground Granary Vault", string bonusType = "Food", int bonusAmount = 3)
        {
            if (string.IsNullOrWhiteSpace(buildingId)) buildingId = "custom_granary_vault";
            if (string.IsNullOrWhiteSpace(name)) name = "Underground Granary Vault";
            if (string.IsNullOrWhiteSpace(bonusType)) bonusType = "Food";
            bonusAmount = Math.Max(1, bonusAmount);

            var sb = new StringBuilder();
            sb.AppendLine("// ═══════════════════════════════════════════════════════════════");
            sb.AppendLine("// CALRADIA FORGE — Settlement Building & Castle Improvement");
            sb.AppendLine("// ─── Generated by ForgeNoviceHub. Safe to copy to your project.");
            sb.AppendLine("// ═══════════════════════════════════════════════════════════════");
            sb.AppendLine();
            sb.AppendLine("// ── PART 1: ModuleData/buildings.xml ─────────────────────────────");
            sb.AppendLine("/*");
            sb.AppendLine("<?xml version=\"1.0\" encoding=\"utf-8\"?>");
            sb.AppendLine("<Buildings>");
            sb.AppendLine($"  <Building id=\"{buildingId}\" name=\"{{={buildingId}_name}}{name}\"");
            sb.AppendLine($"            explanation=\"{{={buildingId}_desc}}Reinforced underground storage enhancing settlement {bonusType.ToLowerInvariant()} reserves.\">");
            sb.AppendLine($"    <BuildingLevel level=\"1\" production_cost=\"1500\" bonus_amount=\"{bonusAmount}\"/>");
            sb.AppendLine($"    <BuildingLevel level=\"2\" production_cost=\"3000\" bonus_amount=\"{bonusAmount * 2}\"/>");
            sb.AppendLine($"    <BuildingLevel level=\"3\" production_cost=\"6000\" bonus_amount=\"{bonusAmount * 3}\"/>");
            sb.AppendLine("  </Building>");
            sb.AppendLine("</Buildings>");
            sb.AppendLine("*/");
            sb.AppendLine();
            sb.AppendLine("// ── PART 2: C# GameModel Decorator (TaleWorlds.CampaignSystem.ComponentInterfaces) ──");
            sb.AppendLine("using TaleWorlds.CampaignSystem;");
            sb.AppendLine("using TaleWorlds.CampaignSystem.ComponentInterfaces;");
            sb.AppendLine("using TaleWorlds.CampaignSystem.Settlements;");
            sb.AppendLine("using TaleWorlds.CampaignSystem.Settlements.Buildings;");
            sb.AppendLine("using TaleWorlds.Localization;");
            sb.AppendLine();
            sb.AppendLine("namespace MyMod.GameModels");
            sb.AppendLine("{");
            sb.AppendLine($"    public class Custom{bonusType}Model : SettlementFoodModel");
            sb.AppendLine("    {");
            sb.AppendLine($"        private readonly SettlementFoodModel _previousModel;");
            sb.AppendLine();
            sb.AppendLine($"        public Custom{bonusType}Model(SettlementFoodModel previousModel)");
            sb.AppendLine("        {");
            sb.AppendLine("            _previousModel = previousModel;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public override ExplainedNumber CalculateDailyFoodVariation(Town town, bool includeDescriptions = false)");
            sb.AppendLine("        {");
            sb.AppendLine("            // Always preserve vanilla/other mod bonuses first");
            sb.AppendLine("            ExplainedNumber result = _previousModel != null");
            sb.AppendLine("                ? _previousModel.CalculateDailyFoodVariation(town, includeDescriptions)");
            sb.AppendLine("                : new ExplainedNumber(0f, includeDescriptions);");
            sb.AppendLine();
            sb.AppendLine("            if (town?.Buildings != null)");
            sb.AppendLine("            {");
            sb.AppendLine("                foreach (Building b in town.Buildings)");
            sb.AppendLine("                {");
            sb.AppendLine($"                    if (b?.BuildingType?.StringId == \"{buildingId}\" && b.CurrentLevel > 0)");
            sb.AppendLine("                    {");
            sb.AppendLine($"                        float bonus = b.CurrentLevel * {bonusAmount}f;");
            sb.AppendLine($"                        result.Add(bonus, new TextObject(\"{{={buildingId}_bonus}}{name}\"));");
            sb.AppendLine("                    }");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            return result;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("// ── REGISTRATION IN SubModule.cs ─────────────────────────────────");
            sb.AppendLine("// protected override void OnGameStart(Game game, IGameStarter starter)");
            sb.AppendLine("// {");
            sb.AppendLine("//     base.OnGameStart(game, starter);");
            sb.AppendLine("//     if (starter is CampaignGameStarter campaignStarter)");
            sb.AppendLine("//     {");
            sb.AppendLine($"//         var prev = campaignStarter.GetExistingModel<SettlementFoodModel>();");
            sb.AppendLine($"//         campaignStarter.AddModel(new Custom{bonusType}Model(prev));");
            sb.AppendLine("//     }");
            sb.AppendLine("// }");
            return sb.ToString();
        }

        // ─────────────────────────────────────────────────────────────────
        // 12. Agent Battle Shout & Formation Tactics
        // ─────────────────────────────────────────────────────────────────

        /// <summary>
        /// Generates an illustrative AgentComponent and MissionLogic source scaffold for custom combat tactics
        /// and battlefield shouts. Review it against the target game's references and lifecycle before use.
        /// </summary>
        public static string GenerateCombatAiComponentScaffold(string componentName = "BattleShoutAgentComponent",
            string missionLogicName = "BattleTacticsMissionLogic", string shoutSoundName = "custom_battle_cry")
        {
            if (string.IsNullOrWhiteSpace(componentName)) componentName = "BattleShoutAgentComponent";
            if (string.IsNullOrWhiteSpace(missionLogicName)) missionLogicName = "BattleTacticsMissionLogic";
            if (string.IsNullOrWhiteSpace(shoutSoundName)) shoutSoundName = "custom_battle_cry";

            ValidateGeneratedIdentifier(componentName, nameof(componentName));
            ValidateGeneratedIdentifier(missionLogicName, nameof(missionLogicName));
            string escapedShoutSoundName = EscapeCSharpStringLiteral(shoutSoundName);

            var sb = new StringBuilder();
            sb.AppendLine("// ═══════════════════════════════════════════════════════════════");
            sb.AppendLine("// CALRADIA FORGE — Agent Battle Shout & Formation Tactics");
            sb.AppendLine("// ─── Generated by ForgeNoviceHub. Review against your target Bannerlord version before use.");
            sb.AppendLine("// ═══════════════════════════════════════════════════════════════");
            sb.AppendLine();
            sb.AppendLine("// ── ARCHITECTURE NOTICE ──────────────────────────────────────────");
            sb.AppendLine("// Meshes and skeletons cannot be added in OnInit(). Defer all 3D setup");
            sb.AppendLine("// to the first OnMissionTick() with a private bool _initialized guard.");
            sb.AppendLine();
            sb.AppendLine("// ── PART 1: AgentComponent (Attached to individual combatants) ─────");
            sb.AppendLine("using TaleWorlds.Engine;");
            sb.AppendLine("using TaleWorlds.MountAndBlade;");
            sb.AppendLine();
            sb.AppendLine("namespace MyMod.Combat");
            sb.AppendLine("{");
            sb.AppendLine($"    public class {componentName} : AgentComponent");
            sb.AppendLine("    {");
            sb.AppendLine("        private float _lastShoutTime = 0f;");
            sb.AppendLine("        private const float ShoutCooldown = 15f;");
            sb.AppendLine();
            sb.AppendLine($"        public {componentName}(Agent agent) : base(agent) {{ }}");
            sb.AppendLine();
            sb.AppendLine("        public void TriggerWarCry()");
            sb.AppendLine("        {");
            sb.AppendLine("            if (Agent == null || !Agent.IsActive()) return;");
            sb.AppendLine("            float curTime = Mission.Current?.CurrentTime ?? 0f;");
            sb.AppendLine("            if (curTime - _lastShoutTime < ShoutCooldown) return;");
            sb.AppendLine();
            sb.AppendLine("            _lastShoutTime = curTime;");
            sb.AppendLine();
            sb.AppendLine("            // 3D positional audio emitter at agent position");
            sb.AppendLine($"            SoundEvent.PlaySound2D(\"{escapedShoutSoundName}\");");
            sb.AppendLine();
            sb.AppendLine("            // Morale boost to nearby friendly formation members");
            sb.AppendLine("            if (Agent.Formation != null)");
            sb.AppendLine("            {");
            sb.AppendLine("                Agent.Formation.ApplyActionOnEachUnit(u =>");
            sb.AppendLine("                {");
            sb.AppendLine("                    if (u != null && u.IsActive())");
            sb.AppendLine("                    {");
            sb.AppendLine("                        // Custom morale recovery code");
            sb.AppendLine("                    }");
            sb.AppendLine("                });");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("// ── PART 2: MissionLogic (Attaches component and manages ticks) ────");
            sb.AppendLine($"    public class {missionLogicName} : MissionLogic");
            sb.AppendLine("    {");
            sb.AppendLine("        private bool _initialized = false;");
            sb.AppendLine();
            sb.AppendLine("        public override void OnMissionTick(float dt)");
            sb.AppendLine("        {");
            sb.AppendLine("            base.OnMissionTick(dt);");
            sb.AppendLine("            if (!_initialized)");
            sb.AppendLine("            {");
            sb.AppendLine("                _initialized = true;");
            sb.AppendLine("                // Safe deferred mesh/skeleton setup point");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public override void OnAgentCreated(Agent agent)");
            sb.AppendLine("        {");
            sb.AppendLine("            base.OnAgentCreated(agent);");
            sb.AppendLine("            if (agent != null && agent.IsHuman)");
            sb.AppendLine("            {");
            sb.AppendLine($"                agent.AddComponent(new {componentName}(agent));");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static void ValidateGeneratedIdentifier(string value, string parameterName)
        {
            bool isValid = value.Length > 0 && string.Equals(
                value, value.Normalize(NormalizationForm.FormC), StringComparison.Ordinal) &&
                (value[0] == '_' || char.IsLetter(value[0]));
            for (int i = 1; isValid && i < value.Length; i++)
            {
                char character = value[i];
                isValid = character == '_' || char.IsLetterOrDigit(character);
            }

            if (!isValid || ReservedCSharpKeywords.Contains(value))
                throw new ArgumentException("The generated type name must be a simple C# identifier in normalization form C and cannot be a reserved keyword.", parameterName);
        }

        private static string EscapeCSharpStringLiteral(string value)
        {
            var escaped = new StringBuilder(value.Length);
            for (int i = 0; i < value.Length; i++)
            {
                char character = value[i];
                switch (character)
                {
                    case '\\': escaped.Append("\\\\"); break;
                    case '"': escaped.Append("\\\""); break;
                    case '\0': escaped.Append("\\0"); break;
                    case '\a': escaped.Append("\\a"); break;
                    case '\b': escaped.Append("\\b"); break;
                    case '\f': escaped.Append("\\f"); break;
                    case '\n': escaped.Append("\\n"); break;
                    case '\r': escaped.Append("\\r"); break;
                    case '\t': escaped.Append("\\t"); break;
                    case '\v': escaped.Append("\\v"); break;
                    default:
                        if (char.IsControl(character) || char.IsSurrogate(character) || character == '\u2028' || character == '\u2029')
                            escaped.Append("\\u").Append(((int)character).ToString("X4", CultureInfo.InvariantCulture));
                        else
                            escaped.Append(character);
                        break;
                }
            }

            return escaped.ToString();
        }
    }
}
