using System;
using System.Text;

namespace CalradiaForge.Sdk
{
    public static class ScaffoldEngine
    {
        public static string Generate(string moduleName, string rootNs = "MyCustomMod")
        {
            if (string.IsNullOrWhiteSpace(rootNs)) rootNs = "MyCustomMod";
            string safeModuleName = moduleName.Replace(" ", "").Replace("-", "");
            safeModuleName = safeModuleName.Replace("Campaign", "CampaignBehaviors");
            bool isUI = safeModuleName.EndsWith("UI") || safeModuleName.EndsWith("HUD") || safeModuleName.Contains("Crosshair") 
                        || safeModuleName.Contains("Overlay") || safeModuleName.Contains("Bars") || safeModuleName.Contains("Compass") 
                        || safeModuleName.Contains("Killfeed") || safeModuleName.Contains("Viewer") || safeModuleName.Contains("Icons") 
                        || safeModuleName.Contains("Sort") || safeModuleName.Contains("Filter") || safeModuleName.Contains("Extender")
                        || safeModuleName.Contains("Extra");

            StringBuilder sb = new StringBuilder(1024);
            
            if (isUI)
            {
                sb.AppendLine("using System;");
                sb.AppendLine("using TaleWorlds.Library;");
                sb.AppendLine();
                sb.AppendLine($"namespace {rootNs}.UI");
                sb.AppendLine("{");
                sb.AppendLine("    /// <summary>");
                sb.AppendLine($"    /// Implements {safeModuleName} UI from Calradia Forge SDK.");
                sb.AppendLine("    /// Generated by Calradia Forge Mod Builder v10.0.1.");
                sb.AppendLine("    /// </summary>");
                sb.AppendLine($"    public class {safeModuleName}VM : ViewModel");
                sb.AppendLine("    {");
                sb.AppendLine("        private bool _isEnabled;");
                sb.AppendLine();
                sb.AppendLine("        [DataSourceProperty]");
                sb.AppendLine("        public bool IsEnabled");
                sb.AppendLine("        {");
                sb.AppendLine("            get => _isEnabled;");
                sb.AppendLine("            set");
                sb.AppendLine("            {");
                sb.AppendLine("                if (_isEnabled != value)");
                sb.AppendLine("                {");
                sb.AppendLine("                    _isEnabled = value;");
                sb.AppendLine("                    OnPropertyChangedWithValue(value, nameof(IsEnabled));");
                sb.AppendLine("                }");
                sb.AppendLine("            }");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine($"        public {safeModuleName}VM()");
                sb.AppendLine("        {");
                sb.AppendLine("            _isEnabled = true;");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine("        public override void RefreshValues()");
                sb.AppendLine("        {");
                sb.AppendLine("            base.RefreshValues();");
                sb.AppendLine("        }");
                sb.AppendLine("    }");
                sb.AppendLine("}");
            }
            else
            {
                sb.AppendLine("using System;");
                sb.AppendLine("using System.Collections.Generic;");
                sb.AppendLine("using TaleWorlds.CampaignSystem;");
                sb.AppendLine("using TaleWorlds.SaveSystem;");
                sb.AppendLine();
                sb.AppendLine($"namespace {rootNs}.CampaignBehaviors");
                sb.AppendLine("{");
                sb.AppendLine("    /// <summary>");
                sb.AppendLine($"    /// Implements {safeModuleName} logic from Calradia Forge SDK.");
                sb.AppendLine("    /// Generated by Calradia Forge Mod Builder v10.0.1.");
                sb.AppendLine("    /// </summary>");
                sb.AppendLine($"    public class {safeModuleName}Behavior : CampaignBehaviorBase");
                sb.AppendLine("    {");
                sb.AppendLine("        private Dictionary<string, int> _customData = new Dictionary<string, int>();");
                sb.AppendLine();
                sb.AppendLine("        public override void RegisterEvents()");
                sb.AppendLine("        {");
                sb.AppendLine("            // Register events here safely");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine("        public override void SyncData(IDataStore dataStore)");
                sb.AppendLine("        {");
                sb.AppendLine("            // Use SyncData to persist primitive fields or basic structs");
                sb.AppendLine($"            dataStore.SyncData(\"{safeModuleName}_data\", ref _customData);");
                sb.AppendLine("            // NOTE: If serializing > 31KB JSON strings, you MUST chunk them into string[] arrays");
                sb.AppendLine("        }");
                sb.AppendLine("    }");
                sb.AppendLine();
                sb.AppendLine("    /// <summary>");
                sb.AppendLine("    /// SaveableTypeDefiner required for native binary serialization of custom types.");
                sb.AppendLine("    /// Uses a high base ID to prevent collisions with native engine (0-100k).");
                sb.AppendLine("    /// </summary>");
                sb.AppendLine($"    public class {safeModuleName}SaveDefiner : SaveableTypeDefiner");
                sb.AppendLine("    {");
                sb.AppendLine($"        public {safeModuleName}SaveDefiner() : base(2_500_000) {{ }}");
                sb.AppendLine();
                sb.AppendLine("        protected override void DefineClassTypes()");
                sb.AppendLine("        {");
                sb.AppendLine("            // AddClassDefinition(typeof(MyCustomStruct), 1);");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine("        protected override void DefineContainerDefinitions()");
                sb.AppendLine("        {");
                sb.AppendLine("            // ConstructContainerDefinition(typeof(Dictionary<string, int>));");
                sb.AppendLine("        }");
                sb.AppendLine("    }");
                sb.AppendLine("}");
            }
            return sb.ToString();
        }
    }
}
