# -*- coding: utf-8 -*-
"""Generate the complete Forge-owned desktop UI catalogs from the English key set."""
import json
from pathlib import Path
from xml.sax.saxutils import escape


def reject_duplicate_json_keys(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f"Duplicate JSON key in desktop extension catalog: {key}")
        result[key] = value
    return result


root = Path(__file__).resolve().parents[1] / "src" / "CalradiaForge.Desktop" / "Resources"
keys = [
    "Ui.AppTitle", "Ui.Subtitle", "Ui.Language", "Ui.Session", "Ui.Areas", "Ui.Search",
    "Ui.RequiredInput", "Ui.Run", "Ui.Cancel", "Ui.Export", "Ui.ExportEvidence", "Ui.Evidence",
    "Ui.EvidenceLedger", "Ui.RawResult", "Ui.Workbench", "Ui.Ready", "Ui.NotRun", "Ui.TemplateHeader", "Ui.Connect",
    "Ui.Operations", "Ui.Pinned", "Ui.Recent", "Ui.AreasLabel", "Ui.CommandPalette", "Ui.Close", "Ui.Context",
    "Ui.TestPermission", "Ui.ReportState", "Ui.RetainedEvidence", "Ui.TechnicalEvidence", "Ui.WorkView", "Ui.InspectionView",
    "Ui.SearchHint", "Ui.ShortcutHint", "Ui.EmptyPinned", "Ui.EmptyRecent", "Ui.ScrollHistory", "Ui.ScrollSections", "Ui.PinnedCount",
    "Ui.RecentCount", "Ui.Pin", "Ui.Unpin", "Ui.ConnectionLive", "Ui.ConnectionOffline",
    "Ui.Theme", "Ui.ThemeWarTable", "Ui.ThemeParchment", "Ui.ThemeHighContrast", "Ui.ThemeHelp",
    "Ui.ThemeContrastWarTable", "Ui.ThemeContrastParchment", "Ui.ThemeContrastHighContrast",
    "Ui.ThemeFallback", "Ui.ThemeApplyFailed", "Ui.HeaderBuild", "Ui.HeaderInspect", "Ui.HeaderVerify",
]
keys.append("Ui.ClearSearch")
keys.extend([
    "Ui.ToolsVisible", "Ui.BrowseFile", "Ui.BrowseFolder", "Ui.DecorativeAccents",
    "Ui.EmptyEvidence", "Ui.EmptyEvidenceAction", "Ui.HeaderSeal", "Ui.WindowClose",
    "Ui.WindowMaximize", "Ui.WindowMinimize", "Ui.WindowRestore",
])
keys.extend([
    "Ui.ApiDeprecation.Name", "Ui.ApiDeprecation.Purpose",
    "Ui.ApiDeprecation.Availability", "Ui.ApiDeprecation.Information",
])
catalogs = {
"en": ["CALRADIA FORGE", "Tactical developer workbench", "LANGUAGE", "SESSION", "WORK AREAS", "Search tools", "REQUIRED INPUT", "Run work order", "Cancel", "Export result", "Export evidence", "EVIDENCE", "EVIDENCE LEDGER", "RAW RESULT", "VERIFIED WORKBENCH", "Ready", "Not run", "Generated by Calradia Forge for {0}. Review this editable starting point."],
"es": ["FORJA DE CALRADIA", "Banco de herramientas táctico para desarrolladores", "IDIOMA", "SESIÓN", "ÁREAS DE TRABAJO", "Buscar herramientas", "ENTRADA REQUERIDA", "Ejecutar orden", "Cancelar", "Exportar resultado", "Exportar evidencia", "EVIDENCIA", "REGISTRO DE EVIDENCIA", "RESULTADO SIN PROCESAR", "BANCO VERIFICADO", "Listo", "No ejecutado", "Generado por Forja de Calradia para {0}. Revisa este punto de partida editable."],
"pt": ["CALRADIA FORGE", "Bancada tática para desenvolvedores", "IDIOMA", "SESSÃO", "ÁREAS DE TRABALHO", "Pesquisar ferramentas", "ENTRADA NECESSÁRIA", "Executar ordem", "Cancelar", "Exportar resultado", "Exportar evidência", "EVIDÊNCIA", "REGISTRO DE EVIDÊNCIAS", "RESULTADO BRUTO", "BANCADA VERIFICADA", "Pronto", "Não executado", "Gerado por Calradia Forge para {0}. Revise este ponto de partida editável."],
"de": ["CALRADIA FORGE", "Taktische Entwicklerwerkbank", "SPRACHE", "SITZUNG", "ARBEITSBEREICHE", "Werkzeuge suchen", "ERFORDERLICHE EINGABE", "Arbeitsauftrag ausführen", "Abbrechen", "Ergebnis exportieren", "Belege exportieren", "BELEGE", "BELEGJOURNAL", "ROHERGEBNIS", "VERIFIZIERTE WERKBANK", "Bereit", "Nicht ausgeführt", "Von Calradia Forge für {0} erstellt. Diese editierbare Vorlage prüfen."],
"fr": ["CALRADIA FORGE", "Atelier tactique pour développeurs", "LANGUE", "SESSION", "ZONES DE TRAVAIL", "Rechercher des outils", "ENTRÉE REQUISE", "Exécuter l'ordre", "Annuler", "Exporter le résultat", "Exporter les preuves", "PREUVES", "REGISTRE DES PREUVES", "RÉSULTAT BRUT", "ATELIER VÉRIFIÉ", "Prêt", "Non exécuté", "Généré par Calradia Forge pour {0}. Vérifiez ce point de départ modifiable."],
"it": ["CALRADIA FORGE", "Banco tattico per sviluppatori", "LINGUA", "SESSIONE", "AREE DI LAVORO", "Cerca strumenti", "INPUT RICHIESTO", "Esegui ordine", "Annulla", "Esporta risultato", "Esporta evidenza", "EVIDENZA", "REGISTRO EVIDENZE", "RISULTATO GREZZO", "BANCO VERIFICATO", "Pronto", "Non eseguito", "Generato da Calradia Forge per {0}. Esamina questo punto di partenza modificabile."],
"pl": ["CALRADIA FORGE", "Taktyczny warsztat deweloperski", "JĘZYK", "SESJA", "OBSZARY PRACY", "Szukaj narzędzi", "WYMAGANE DANE", "Uruchom zlecenie", "Anuluj", "Eksportuj wynik", "Eksportuj dowody", "DOWODY", "DZIENNIK DOWODÓW", "SUROWY WYNIK", "ZWERYFIKOWANY WARSZTAT", "Gotowe", "Nie uruchomiono", "Wygenerowane przez Calradia Forge dla {0}. Sprawdź ten edytowalny punkt wyjścia."],
"ru": ["CALRADIA FORGE", "Тактическая рабочая станция разработчика", "ЯЗЫК", "СЕАНС", "РАБОЧИЕ ОБЛАСТИ", "Поиск инструментов", "ТРЕБУЕМЫЕ ДАННЫЕ", "Выполнить задачу", "Отмена", "Экспорт результата", "Экспорт доказательств", "ДОКАЗАТЕЛЬСТВА", "ЖУРНАЛ ДОКАЗАТЕЛЬСТВ", "СЫРОЙ РЕЗУЛЬТАТ", "ПРОВЕРЕННАЯ СТАНЦИЯ", "Готово", "Не выполнено", "Создано Calradia Forge для {0}. Проверьте эту редактируемую отправную точку."],
"tr": ["CALRADIA FORGE", "Taktik geliştirici tezgahı", "DİL", "OTURUM", "ÇALIŞMA ALANLARI", "Araçları ara", "GEREKLİ GİRDİ", "İş emrini çalıştır", "İptal", "Sonucu dışa aktar", "Kanıtı dışa aktar", "KANIT", "KANIT DEFTERİ", "HAM SONUÇ", "DOĞRULANMIŞ TEZGAH", "Hazır", "Çalıştırılmadı", "Calradia Forge tarafından {0} için oluşturuldu. Bu düzenlenebilir başlangıç noktasını inceleyin."],
"zh-HANS": ["CALRADIA FORGE", "战术开发者工作台", "语言", "会话", "工作区", "搜索工具", "所需输入", "运行工作指令", "取消", "导出结果", "导出证据", "证据", "证据账本", "原始结果", "已验证工作台", "就绪", "未运行", "由 Calradia Forge 为 {0} 生成。请审阅此可编辑起点。"],
"zh-HANT": ["CALRADIA FORGE", "戰術開發者工作台", "語言", "工作階段", "工作區", "搜尋工具", "必要輸入", "執行工作指令", "取消", "匯出結果", "匯出證據", "證據", "證據帳本", "原始結果", "已驗證工作台", "就緒", "未執行", "由 Calradia Forge 為 {0} 產生。請檢閱此可編輯起點。"],
"ja": ["CALRADIA FORGE", "戦術開発者ワークベンチ", "言語", "セッション", "作業領域", "ツールを検索", "必要な入力", "作業指示を実行", "キャンセル", "結果をエクスポート", "証拠をエクスポート", "証拠", "証拠台帳", "生の結果", "検証済みワークベンチ", "準備完了", "未実行", "Calradia Forge が {0} 向けに生成しました。この編集可能な開始点を確認してください。"],
"ko": ["CALRADIA FORGE", "전술 개발자 작업대", "언어", "세션", "작업 영역", "도구 검색", "필수 입력", "작업 지시 실행", "취소", "결과 내보내기", "증거 내보내기", "증거", "증거 장부", "원시 결과", "검증된 작업대", "준비됨", "실행 안 됨", "Calradia Forge가 {0}용으로 생성했습니다. 이 편집 가능한 시작점을 검토하세요."],
}
extension_path = Path(__file__).resolve().parents[1] / "localization" / "desktop-extensions.json"
extension_catalog = json.loads(extension_path.read_text(encoding="utf-8"), object_pairs_hook=reject_duplicate_json_keys)
extension_languages = set(catalogs)
extension_keys = sorted(extension_catalog)
if len(keys) != len(set(keys)):
    raise RuntimeError("Desktop base resource keys contain duplicates")
if set(extension_catalog).intersection(keys):
    raise RuntimeError("Desktop extension catalog duplicates an existing resource key")
for resource_key, translations in extension_catalog.items():
    if not isinstance(translations, dict) or set(translations) != extension_languages:
        raise RuntimeError(f"Desktop extension has incomplete language coverage: {resource_key}")
    if any(not isinstance(value, str) or not value.strip() for value in translations.values()):
        raise RuntimeError(f"Desktop extension has an empty or invalid translation: {resource_key}")
keys.extend(extension_keys)
connect_labels = {
    "en": "Connect", "es": "Conectar", "pt": "Conectar", "de": "Verbinden", "fr": "Connecter",
    "it": "Connetti", "pl": "Połącz", "ru": "Подключить", "tr": "Bağlan",
    "zh-HANS": "连接", "zh-HANT": "連線", "ja": "接続", "ko": "연결",
}
extra_en = ["OPERATIONS", "PINNED", "RECENT", "AREAS", "COMMAND PALETTE", "CLOSE", "CONTEXT", "TEST PERMISSION", "REPORT STATE", "RETAINED EVIDENCE", "TECHNICAL EVIDENCE / READ ONLY", "WORK VIEW", "INSPECTION VIEW", "Search by title, identifier, or category", "Ctrl+K palette   Ctrl+F search   Ctrl+Enter run   Esc close", "No pinned tools yet", "No recent tools yet", "Scroll history", "Scroll sections", "Pinned tools", "Recent tools", "Pin", "Unpin", "Forge session online", "Forge session offline", "THEME", "War Table", "Parchment Light", "High Contrast", "Choose the visual system", "Contrast: tactical default", "Contrast: warm parchment", "Contrast: maximum focus", "Theme preference was unknown; War Table was restored.", "Theme change failed; the current theme was kept."]
extra_catalogs = {
    "en": extra_en,
    "es": ["OPERACIONES", "FIJADAS", "RECIENTES", "ÁREAS", "PALETA DE COMANDOS", "CERRAR", "CONTEXTO", "PERMISO DE PRUEBAS", "ESTADO DEL INFORME", "EVIDENCIA RETENIDA", "EVIDENCIA TÉCNICA / SOLO LECTURA", "VISTA DE TRABAJO", "VISTA DE INSPECCIÓN", "Buscar por título, identificador o categoría", "Ctrl+K paleta   Ctrl+F buscar   Ctrl+Enter ejecutar   Esc cerrar", "Aún no hay herramientas fijadas", "Aún no hay herramientas recientes", "Desplazar historial", "Desplazar secciones", "Herramientas fijadas", "Herramientas recientes", "Fijar", "Quitar fijación", "Sesión Forge conectada", "Sesión Forge desconectada", "TEMA", "Mesa de guerra", "Pergamino claro", "Alto contraste", "Elige el sistema visual", "Contraste: predeterminado táctico", "Contraste: pergamino cálido", "Contraste: foco máximo", "La preferencia de tema no era válida; se restauró Mesa de guerra.", "No se pudo cambiar el tema; se conserva el tema actual."],
    "pt": ["OPERAÇÕES", "FIXADAS", "RECENTES", "ÁREAS", "PALETA DE COMANDOS", "FECHAR", "CONTEXTO", "PERMISSÃO DE TESTE", "ESTADO DO RELATÓRIO", "EVIDÊNCIA RETIDA", "EVIDÊNCIA TÉCNICA / SOMENTE LEITURA", "VISÃO DE TRABALHO", "VISÃO DE INSPEÇÃO", "Pesquisar por título, identificador ou categoria", "Ctrl+K paleta   Ctrl+F pesquisar   Ctrl+Enter executar   Esc fechar", "Ainda não há ferramentas fixadas", "Ainda não há ferramentas recentes", "Rolar histórico", "Rolar seções", "Ferramentas fixadas", "Ferramentas recentes", "Fixar", "Desafixar", "Sessão Forge conectada", "Sessão Forge desconectada", "TEMA", "Mesa de guerra", "Pergaminho claro", "Alto contraste", "Escolha o sistema visual", "Contraste: tático padrão", "Contraste: pergaminho quente", "Contraste: foco máximo", "A preferência de tema era inválida; Mesa de guerra foi restaurada.", "Não foi possível trocar o tema; o tema atual foi mantido."],
    "de": ["OPERATIONEN", "ANGEHEFTET", "KÜRZLICH", "BEREICHE", "BEFEHLSPALETTE", "SCHLIESSEN", "KONTEXT", "TESTBERECHTIGUNG", "BERICHTSSTATUS", "BEHALTENE BELEGE", "TECHNISCHER BELEG / NUR LESEN", "ARBEITSANSICHT", "INSPEKTIONSANSICHT", "Nach Titel, Kennung oder Bereich suchen", "Ctrl+K Palette   Ctrl+F Suche   Ctrl+Enter ausführen   Esc schließen", "Noch keine angehefteten Werkzeuge", "Noch keine aktuellen Werkzeuge", "Verlauf scrollen", "Bereiche scrollen", "Angeheftete Werkzeuge", "Aktuelle Werkzeuge", "Anheften", "Lösen", "Forge-Sitzung online", "Forge-Sitzung offline", "THEMA", "Kriegstisch", "Pergament hell", "Hoher Kontrast", "Visuelles System wählen", "Kontrast: taktischer Standard", "Kontrast: warmes Pergament", "Kontrast: maximaler Fokus", "Die Theme-Einstellung war ungültig; Kriegstisch wurde wiederhergestellt.", "Theme-Wechsel fehlgeschlagen; das aktuelle Theme bleibt erhalten."],
    "fr": ["OPÉRATIONS", "ÉPINGLÉS", "RÉCENTS", "ZONES", "PALETTE DE COMMANDES", "FERMER", "CONTEXTE", "AUTORISATION DE TEST", "ÉTAT DU RAPPORT", "PREUVES CONSERVÉES", "PREUVE TECHNIQUE / LECTURE SEULE", "VUE DE TRAVAIL", "VUE D’INSPECTION", "Rechercher par titre, identifiant ou zone", "Ctrl+K palette   Ctrl+F rechercher   Ctrl+Entrée exécuter   Échap fermer", "Aucun outil épinglé", "Aucun outil récent", "Faire défiler l’historique", "Faire défiler les sections", "Outils épinglés", "Outils récents", "Épingler", "Désépingler", "Session Forge en ligne", "Session Forge hors ligne", "THÈME", "Table de guerre", "Parchemin clair", "Contraste élevé", "Choisir le système visuel", "Contraste : tactique par défaut", "Contraste : parchemin chaud", "Contraste : focus maximal", "La préférence de thème était invalide ; Table de guerre restaurée.", "Le changement de thème a échoué ; le thème actuel est conservé."],
}
header_badges = {
    "en": ["BUILD", "INSPECT", "VERIFY"],
    "es": ["CREAR", "INSPECCIONAR", "VERIFICAR"],
    "pt": ["CRIAR", "INSPECIONAR", "VERIFICAR"],
    "de": ["ERSTELLEN", "PRÜFEN", "VALIDIEREN"],
    "fr": ["CRÉER", "INSPECTER", "VÉRIFIER"],
    "it": ["CREA", "ISPEZIONA", "VERIFICA"],
    "pl": ["TWÓRZ", "SPRAWDŹ", "WERYFIKUJ"],
    "ru": ["СОЗДАВАТЬ", "ПРОВЕРЯТЬ", "ПРОВЕРИТЬ"],
    "tr": ["OLUŞTUR", "İNCELE", "DOĞRULA"],
    "zh-HANS": ["构建", "检查", "验证"],
    "zh-HANT": ["建置", "檢查", "驗證"],
    "ja": ["構築", "検査", "検証"],
    "ko": ["빌드", "검사", "검증"],
}
clear_search_labels = {
    "en": "Clear search", "es": "Limpiar búsqueda", "pt": "Limpar pesquisa", "de": "Suche löschen",
    "fr": "Effacer la recherche", "it": "Cancella ricerca", "pl": "Wyczyść wyszukiwanie",
    "ru": "Очистить поиск", "tr": "Aramayı temizle", "zh-HANS": "清除搜索", "zh-HANT": "清除搜尋",
    "ja": "検索をクリア", "ko": "검색 지우기",
}
search_hint_labels = {
    "en": "Search by title, identifier, or category",
    "es": "Buscar por título, identificador o categoría",
    "pt": "Pesquisar por título, identificador ou categoria",
    "de": "Nach Titel, Kennung oder Kategorie suchen",
    "fr": "Rechercher par titre, identifiant ou catégorie",
    "it": "Cerca per titolo, identificatore o categoria",
    "pl": "Szukaj według tytułu, identyfikatora lub kategorii",
    "ru": "Поиск по названию, идентификатору или категории",
    "tr": "Başlığa, tanımlayıcıya veya kategoriye göre ara",
    "zh-HANS": "按标题、标识符或类别搜索",
    "zh-HANT": "依標題、識別碼或類別搜尋",
    "ja": "タイトル、識別子、カテゴリで検索",
    "ko": "제목, 식별자 또는 범주로 검색",
}
additional_labels = {
    "en": ["Tools visible", "Browse files", "Browse folders", "Decorative artwork", "No evidence retained yet.", "Open command palette", "Open command palette from the Forge seal", "Close", "Maximize", "Minimize", "Restore"],
    "es": ["Herramientas visibles", "Buscar archivos", "Buscar carpetas", "Adornos decorativos", "Aún no hay evidencias guardadas.", "Abrir la paleta de comandos", "Abrir la paleta desde el sello de Forge", "Cerrar", "Maximizar", "Minimizar", "Restaurar"],
    "pt": ["Ferramentas visíveis", "Procurar arquivos", "Procurar pastas", "Arte decorativa", "Ainda não há evidências retidas.", "Abrir a paleta de comandos", "Abrir a paleta pelo selo da Forge", "Fechar", "Maximizar", "Minimizar", "Restaurar"],
    "de": ["Sichtbare Werkzeuge", "Dateien durchsuchen", "Ordner durchsuchen", "Dekorative Gestaltung", "Noch keine Belege gespeichert.", "Befehlspalette öffnen", "Befehlspalette über das Forge-Siegel öffnen", "Schließen", "Maximieren", "Minimieren", "Wiederherstellen"],
    "fr": ["Outils visibles", "Parcourir les fichiers", "Parcourir les dossiers", "Ornements décoratifs", "Aucune preuve conservée pour le moment.", "Ouvrir la palette de commandes", "Ouvrir la palette depuis le sceau Forge", "Fermer", "Agrandir", "Réduire", "Restaurer"],
    "it": ["Strumenti visibili", "Sfoglia file", "Sfoglia cartelle", "Decorazioni", "Nessuna evidenza conservata.", "Apri la tavolozza dei comandi", "Apri la tavolozza dal sigillo Forge", "Chiudi", "Ingrandisci", "Riduci", "Ripristina"],
    "pl": ["Widoczne narzędzia", "Przeglądaj pliki", "Przeglądaj foldery", "Dekoracje", "Brak zachowanych dowodów.", "Otwórz paletę poleceń", "Otwórz paletę z pieczęci Forge", "Zamknij", "Maksymalizuj", "Minimalizuj", "Przywróć"],
    "ru": ["Видимые инструменты", "Выбрать файлы", "Выбрать папки", "Декоративное оформление", "Сохранённых свидетельств пока нет.", "Открыть палитру команд", "Открыть палитру через печать Forge", "Закрыть", "Развернуть", "Свернуть", "Восстановить"],
    "tr": ["Görünür araçlar", "Dosyalara göz at", "Klasörlere göz at", "Dekoratif süsler", "Henüz saklanan kanıt yok.", "Komut paletini aç", "Forge mühründen komut paletini aç", "Kapat", "Büyüt", "Küçült", "Geri yükle"],
    "zh-HANS": ["可见工具", "浏览文件", "浏览文件夹", "装饰图案", "尚无保留的证据。", "打开命令面板", "从 Forge 印记打开命令面板", "关闭", "最大化", "最小化", "还原"],
    "zh-HANT": ["可見工具", "瀏覽檔案", "瀏覽資料夾", "裝飾圖樣", "目前沒有保留的證據。", "開啟命令面板", "從 Forge 印記開啟命令面板", "關閉", "最大化", "最小化", "還原"],
    "ja": ["表示中のツール", "ファイルを参照", "フォルダーを参照", "装飾", "保持された証拠はありません。", "コマンドパレットを開く", "Forge のシールからコマンドパレットを開く", "閉じる", "最大化", "最小化", "元に戻す"],
    "ko": ["표시 중인 도구", "파일 찾아보기", "폴더 찾아보기", "장식 요소", "보관된 증거가 없습니다.", "명령 팔레트 열기", "Forge 인장으로 명령 팔레트 열기", "닫기", "최대화", "최소화", "복원"],
}
api_deprecation_labels = {
    "en": [
        "API Deprecation Analysis — Unavailable",
        "Unavailable until a verified, versioned TaleWorlds API deprecation catalog is available.",
        "Unavailable: no verified, versioned TaleWorlds API deprecation catalog is configured.",
        "This route does not classify API usage as deprecated. Analysis may be enabled only after a verified catalog identifies the exact TaleWorlds API version it covers.",
    ],
    "es": [
        "Análisis de obsolescencia de API — No disponible",
        "No disponible hasta contar con un catálogo de obsolescencias de API de TaleWorlds verificado y versionado.",
        "No disponible: no hay configurado un catálogo de obsolescencias de API de TaleWorlds verificado y versionado.",
        "Esta ruta no clasifica usos de API como obsoletos. El análisis solo podrá habilitarse cuando un catálogo verificado identifique la versión exacta de la API de TaleWorlds que cubre.",
    ],
    "pt": [
        "Análise de obsolescência de API — Indisponível",
        "Indisponível até existir um catálogo de obsolescência da API da TaleWorlds verificado e versionado.",
        "Indisponível: não há um catálogo de obsolescência da API da TaleWorlds verificado e versionado configurado.",
        "Esta rota não classifica o uso de APIs como obsoleto. A análise só poderá ser habilitada quando um catálogo verificado identificar a versão exata da API da TaleWorlds abrangida.",
    ],
    "de": [
        "API-Veraltungsanalyse — Nicht verfügbar",
        "Nicht verfügbar, bis ein verifizierter, versionierter Katalog veralteter TaleWorlds-APIs vorliegt.",
        "Nicht verfügbar: Es ist kein verifizierter, versionierter TaleWorlds-API-Katalog für veraltete APIs eingerichtet.",
        "Diese Route stuft API-Verwendungen nicht als veraltet ein. Die Analyse darf erst aktiviert werden, wenn ein verifizierter Katalog die genaue abgedeckte TaleWorlds-API-Version nennt.",
    ],
    "fr": [
        "Analyse des API dépréciées — Indisponible",
        "Indisponible jusqu’à ce qu’un catalogue vérifié et versionné des API TaleWorlds dépréciées soit disponible.",
        "Indisponible : aucun catalogue vérifié et versionné des API TaleWorlds dépréciées n’est configuré.",
        "Cette route ne classe pas l’utilisation d’API comme dépréciée. L’analyse ne pourra être activée qu’après qu’un catalogue vérifié aura identifié la version exacte de l’API TaleWorlds couverte.",
    ],
    "it": [
        "Analisi delle API deprecate — Non disponibile",
        "Non disponibile finché non sarà disponibile un catalogo verificato e versionato delle API TaleWorlds deprecate.",
        "Non disponibile: non è configurato alcun catalogo verificato e versionato delle API TaleWorlds deprecate.",
        "Questo percorso non classifica l’uso delle API come deprecato. L’analisi potrà essere abilitata solo quando un catalogo verificato identificherà la versione esatta dell’API TaleWorlds coperta.",
    ],
    "pl": [
        "Analiza wycofanych API — niedostępna",
        "Niedostępna do czasu udostępnienia zweryfikowanego, wersjonowanego katalogu wycofanych API TaleWorlds.",
        "Niedostępna: nie skonfigurowano zweryfikowanego, wersjonowanego katalogu wycofanych API TaleWorlds.",
        "Ta ścieżka nie klasyfikuje użycia API jako wycofanego. Analizę można włączyć dopiero po wskazaniu przez zweryfikowany katalog dokładnej wersji API TaleWorlds, której dotyczy.",
    ],
    "ru": [
        "Анализ устаревших API — недоступен",
        "Недоступен до появления проверенного версионируемого каталога устаревших API TaleWorlds.",
        "Недоступен: проверенный версионируемый каталог устаревших API TaleWorlds не настроен.",
        "Этот маршрут не классифицирует использование API как устаревшее. Анализ можно включить только после того, как проверенный каталог укажет точную версию API TaleWorlds, которую он охватывает.",
    ],
    "tr": [
        "API Kullanımdan Kaldırma Analizi — Kullanılamıyor",
        "Doğrulanmış ve sürümlenmiş bir TaleWorlds API kullanımdan kaldırma kataloğu sağlanana kadar kullanılamaz.",
        "Kullanılamıyor: doğrulanmış ve sürümlenmiş bir TaleWorlds API kataloğu yapılandırılmamış.",
        "Bu rota API kullanımını kullanımdan kaldırılmış olarak sınıflandırmaz. Analiz ancak doğrulanmış bir katalog kapsadığı TaleWorlds API sürümünü açıkça belirttikten sonra etkinleştirilebilir.",
    ],
    "zh-HANS": [
        "API 弃用分析 — 暂不可用",
        "在获得经过验证且带版本信息的 TaleWorlds API 弃用目录前，此功能不可用。",
        "暂不可用：尚未配置经过验证且带版本信息的 TaleWorlds API 弃用目录。",
        "此路线不会将 API 用法判定为已弃用。只有经过验证的目录明确标出其涵盖的 TaleWorlds API 版本后，才能启用分析。",
    ],
    "zh-HANT": [
        "API 棄用分析 — 暫不可用",
        "在取得經過驗證且附有版本資訊的 TaleWorlds API 棄用目錄前，此功能不可用。",
        "暫不可用：尚未設定經過驗證且附有版本資訊的 TaleWorlds API 棄用目錄。",
        "此路徑不會將 API 用法判定為已棄用。只有在經過驗證的目錄明確標示涵蓋的 TaleWorlds API 版本後，才能啟用分析。",
    ],
    "ja": [
        "API 非推奨分析 — 利用不可",
        "検証済みでバージョンが明記された TaleWorlds API 非推奨カタログが用意されるまで利用できません。",
        "利用不可: 検証済みでバージョンが明記された TaleWorlds API 非推奨カタログが設定されていません。",
        "このルートは API の使用を非推奨と判定しません。検証済みカタログが対象となる TaleWorlds API の正確なバージョンを明示した後にのみ、分析を有効化できます。",
    ],
    "ko": [
        "API 사용 중단 분석 — 사용할 수 없음",
        "검증되고 버전이 명시된 TaleWorlds API 사용 중단 카탈로그가 마련될 때까지 사용할 수 없습니다.",
        "사용할 수 없음: 검증되고 버전이 명시된 TaleWorlds API 사용 중단 카탈로그가 설정되지 않았습니다.",
        "이 경로는 API 사용을 사용 중단으로 판정하지 않습니다. 검증된 카탈로그가 적용 대상인 TaleWorlds API의 정확한 버전을 명시한 뒤에만 분석을 활성화할 수 있습니다.",
    ],
}
for code, values in catalogs.items():
    values.append(connect_labels[code])
    values.extend(extra_catalogs.get(code, extra_en))
    values.extend(header_badges[code])
    values.append(clear_search_labels[code])
    values.extend(additional_labels[code])
    values.extend(api_deprecation_labels[code])
    values.extend(extension_catalog[resource_key][code] for resource_key in extension_keys)
    if len(values) != len(keys):
        raise RuntimeError(f"{code} does not match English key count")
    values[keys.index("Ui.SearchHint")] = search_hint_labels[code]
    body = "\n".join(f' <sys:String x:Key="{key}">{escape(value)}</sys:String>' for key, value in zip(keys, values))
    (root / f"Strings.{code}.xaml").write_text(
        '<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" xmlns:sys="clr-namespace:System;assembly=mscorlib">\n'
        + body + '\n</ResourceDictionary>\n',
        encoding="utf-8",
    )
print(f"Generated {len(catalogs)} desktop resource dictionaries with {len(keys)} keys each.")
