<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0-windows</TargetFramework><UseWPF>true</UseWPF><UseAppHost>false</UseAppHost></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/CalradiaForge.Core/CalradiaForge.Core.csproj" />
    <ProjectReference Include="../../src/CalradiaForge.Desktop/CalradiaForge.Desktop.csproj" />
    <PackageReference Include="AsmResolver.DotNet" Version="6.0.1" />
    <None Include="../../src/CalradiaForge.Desktop/MainWindow.xaml" Link="Ui/MainWindow.xaml" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../../src/CalradiaForge.Desktop/MainWindow.xaml.cs" Link="Ui/MainWindow.xaml.cs" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../../localization/*.xml" Link="Ui/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
