<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net472</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
    <Optimize>true</Optimize>
    <DebugType>none</DebugType>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/CalradiaForge.Sdk/CalradiaForge.Sdk.csproj" />
    <ProjectReference Include="../../src/CalradiaForge.Core/CalradiaForge.Core.csproj" />
  </ItemGroup>
</Project>
